### ISSUE TITLE
epoll_ctl: mod bad file descriptor on goes restart

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#116]
On repeated goes restart test, particularly with interfaces in containers, sometimes the following panic happens.  This is due to small window where epoll is active but an interface(and file descriptor) associated with it has been moved or removed.
```
Mar 13 11:34:12 invader34 goes.vnetd[15334]: panic: epoll_ctl: mod bad file descriptor
Mar 13 11:34:12 invader34 goes.vnetd[15334]:
Mar 13 11:34:12 invader34 goes.vnetd[15334]: goroutine 50 [running]:
Mar 13 11:34:12 invader34 goes.vnetd[15334]: github.com/platinasystems/go/elib/iomux.(*Mux).Update(0x194c9a0, 0x18ff320, 0xc42057b180)
Mar 13 11:34:12 invader34 goes.vnetd[15334]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/iomux/epoll.go:135 +0x199
Mar 13 11:34:12 invader34 goes.vnetd[15334]: github.com/platinasystems/go/elib/iomux.Update(0x18ff320, 0xc42057b180)
Mar 13 11:34:12 invader34 goes.vnetd[15334]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/iomux/iomux.go:57 +0x41
Mar 13 11:34:12 invader34 goes.vnetd[15334]: github.com/platinasystems/go/vnet/unix.(*tuntap_interface).ReadReady(0xc42057b180, 0x0, 0x0)
Mar 13 11:34:12 invader34 goes.vnetd[15334]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/rx.go:376 +0x499
Mar 13 11:34:12 invader34 goes.vnetd[15334]: github.com/platinasystems/go/elib/iomux.(*Mux).do(0x194c9a0, 0xc4202d7380)
Mar 13 11:34:12 invader34 goes.vnetd[15334]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/iomux/epoll.go:158 +0x167
Mar 13 11:34:12 invader34 goes.vnetd[15334]: github.com/platinasystems/go/elib/iomux.(*Mux).EventPoll(0x194c9a0)
Mar 13 11:34:12 invader34 goes.vnetd[15334]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/iomux/epoll.go:178 +0xd1
Mar 13 11:34:12 invader34 goes.vnetd[15334]: github.com/platinasystems/go/elib/loop.(*Loop).eventPoller(0xc420209818, 0x18f1040, 0x194c9a0)
Mar 13 11:34:12 invader34 goes.vnetd[15334]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:296 +0x57
Mar 13 11:34:12 invader34 goes.vnetd[15334]: created by github.com/platinasystems/go/elib/loop.(*Loop).startEventPoller
Mar 13 11:34:12 invader34 goes.vnetd[15334]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:299 +0x53
```

**Comment by fszyang** [comment]
Fixed in commit 0ddf2cbada2e8dd2da5db06d4aad4e013921f8c2
