### ISSUE TITLE
goes restart is creating vnetd panic if sub-port interfaces are created without speed set

### ISSUE THREAD

**Issue by jignesh045** [platinasystems/go#131]
Issue statement: goes restart is creating vnetd panic if sub-port interfaces are created without speed set

Environment: 

```
root@invader45:/home/jignesh# goes version
github.com/platinasystems/go: v0.41-332-g3d923a20
github.com/platinasystems/fe1: v0.2-529-ga5f1fd4
github.com/platinasystems/firmware-fe1a: v0.2
root@invader45:/home/jignesh#
root@invader45:/home/jignesh# goes hget platina-mk1 packages | grep version:
    version: 3d923a20338fc8460211756d67efae0ef8f0408a
    version: a5f1fd4d4e7965f9efd954131f232670b59779ea
    version: 60f39141fbbf78ddb2260dba74c68f2789374f18
root@invader45:/home/jignesh#
root@invader45:/home/jignesh# dpkg --list | grep kernel
ii  kmod                           18-3                             amd64        tools for managing Linux kernel modules
ii  libdrm2:amd64                  2.4.58-2                         amd64        Userspace interface to kernel DRM services -- runtime
ii  linux-image-4.13.0-platina-mk1 4.13-134-g39fbcf8c984f           amd64        Linux kernel, version 4.13.0-platina-mk1
ii  rsyslog                        8.4.2-1+deb8u2                   amd64        reliable system and kernel logging daemon
root@invader45:/home/jignesh#
```
Steps:

1. Create below script

```
root@invader45:/home/jignesh# cat issue.sh
#! /bin/bash
goes stop
rmmod platina-mk1
modprobe platina-mk1
for (( i=1; i <=32; i++ ))
        do
           for (( j=1; j<=4; j++))

             do

                ip link add eth-$i-$j type xeth
                ip link set eth-$i-$j up
                ethtool -s eth-$i-1 speed 100000 autoneg off
                ifconfig eth-$i-$j 10.$i.$j.29/24
#               ip add add 10.0.$i.29/24 dev eth-$i-1
#               sleep 5
             done
        done

goes start

root@invader45:/home/jignesh#
```
2. Before executing script goes status is OK.

```
root@invader45:/home/jignesh# goes status
GOES status
======================
  Mode            - SRIOV
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK
root@invader45:/home/jignesh#
```

3. Execute the script and observe goes status.

```
root@invader45:/home/jignesh# ./issue.sh
root@invader45:/home/jignesh#

root@invader45:/home/jignesh# goes status
GOES status
======================
  Mode            - SRIOV
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - Not OK
status: vnetd daemon not responding
root@invader45:/home/jignesh#
```

4. In above script, i have only assigned speed to eth-$i-1 interface. Rest interface should come up with default speed set something like autoneg. I have assigned different speed and observed below logs.

Below are the /var/log/syslog when i have configured the speed in above script as "**ethtool -s eth-$i-1 speed 100000 autoneg off**"

```
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce01 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce05 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce03 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce02 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce00 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce09 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce04 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce10 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce23 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce06 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce20 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce11 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce27 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce25 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce08 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce24 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce12 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce13 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce15 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce14 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce26 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce16 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce29 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce17 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce30 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce31 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce07 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce18 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce28 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce19 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce22 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce21 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce22 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce15 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce03 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce30 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce20 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce06 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce23 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce05 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce17 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce29 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce28 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce00 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce08 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce12 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce01 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce21 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce09 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce31 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce14 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce18 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce16 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce11 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce25 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce07 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce02 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce19 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce24 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce26 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce13 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce27 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce04 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:48 debian goes.vnetd[4349]: Error port mode: ce10 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:49 debian goes.vnetd[4349]: SetSpeed   eth-24-1, laneMask=1111, firstLaneMask=   1 Nlanes=4
Aug  8 01:52:49 debian goes.vnetd[4349]: Error port mode: ce23 m0=0xf, m1=0x2, m2=0x4, m3=0x8
Aug  8 01:52:49 debian goes.vnetd[4349]:   Set portMode=4
Aug  8 01:52:49 debian goes.vnetd[4349]:   eth-24-1 Set FEC, Cl91=false, CL74=true, FecEnable=false
Aug  8 01:52:49 debian goes.vnetd[4349]:   eth-24-1 Set speed = 1e+11 media=optics
Aug  8 01:52:49 debian goes.vnetd[4349]:   eth-24-1 Set PLL mult = 7
Aug  8 01:52:49 debian goes.vnetd[4349]:   eth-24-2 Set FEC, Cl91=false, CL74=true, FecEnable=false
Aug  8 01:52:49 debian goes.vnetd[4349]:   eth-24-2 Set speed = 0 media=optics
Aug  8 01:52:49 debian goes.vnetd[4349]: eventHandler: panic vnet: unsupported speed/lane mask combination 0.000000e+00 0x2
Aug  8 01:52:49 debian goes.vnetd[4349]: panic: vnet: unsupported speed/lane mask combination 0.000000e+00 0x2
Aug  8 01:52:49 debian goes.vnetd[4349]: goroutine 38 [running]:
Aug  8 01:52:49 debian goes.vnetd[4349]: runtime/debug.Stack(0xc33fc0, 0xc42080e450, 0xc425397628)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /usr/lib/go-1.9/src/runtime/debug/stack.go:24 +0xa7
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler.func1(0xc42013c418, 0xc42013c970)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:189 +0x1c9
Aug  8 01:52:49 debian goes.vnetd[4349]: panic(0xc33fc0, 0xc42080e430)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/fe1/internal/phy.(*HundredGig).SetSpeed(0xc421107f40, 0x19aabe0, 0xc421137f00, 0x42374876e8000000, 0x0)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/phy/hundred_gig.go:803 +0x11d5
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/fe1/internal/port.(*PortBlock).setPhySpeed(0xc421105bd8, 0x19aabe0, 0xc421137f00)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/port/port.go:212 +0xd4
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/fe1/internal/port.(*PortBlock).SetPortEnable(0xc421105bd8, 0x19aabe0, 0xc421137f00, 0xc423abf301)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/port/port.go:272 +0x17b
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/fe1/internal/fe1a.(*Port).port_up_down(0xc421137f00, 0xc420c66000, 0x5900000001)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/fe1a/port_init.go:902 +0x62
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).swIfAdminUpDown(0xc420c66000, 0xc42013c418, 0x100000059, 0x0, 0x0)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/fe1a/l3_interface.go:732 +0x120
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).(github.com/platinasystems/fe1/internal/fe1a.swIfAdminUpDown)-fm(0xc42013c418, 0x100000059, 0xc42073ef40, 0xc425397cb0)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/fe1a/l3.go:30 +0x45
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/go/vnet.(*SwIf).SetAdminUp(0xc42463a590, 0xc42013c418, 0xc420785001, 0x59, 0x100000059)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/interface.go:344 +0xca
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/go/vnet.Si.SetAdminUp(0xc400000059, 0xc42013c418, 0x100000001, 0x1a0cf00, 0x0)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/interface.go:354 +0x62
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc422e27640)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:465 +0x88f
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/go/elib/loop.(*nodeEvent).do(0xc422e276c0)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:158 +0x98
Aug  8 01:52:49 debian goes.vnetd[4349]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc42013c418, 0x199b380, 0xc42013c968)
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:228 +0xa3
Aug  8 01:52:49 debian goes.vnetd[4349]: created by github.com/platinasystems/go/elib/loop.(*Node).maybeStartEventHandler.func1
Aug  8 01:52:49 debian goes.vnetd[4349]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:389 +0x271
Aug  8 01:52:50 debian kernel: ixgbe 0000:03:00.0 eth1: NIC Link is Up 10 Gbps, Flow Control: RX/TX
Aug  8 01:52:50 debian kernel: ixgbe 0000:03:00.1 eth2: NIC Link is Up 10 Gbps, Flow Control: RX/TX
```

Below are the /var/log/syslog when i have configured the speed in above script as "**ethtool -s eth-$i-1 speed 10000 autoneg off**"

```
Aug  8 01:58:34 debian kernel: ixgbe 0000:03:00.0 eth1: NIC Link is Down
Aug  8 01:58:34 debian kernel: ixgbe 0000:03:00.1 eth2: NIC Link is Down
Aug  8 01:58:35 debian kernel: vfio-pci 0000:04:00.0: enabling device (0000 -> 0002)
Aug  8 01:58:35 debian kernel: vfio-pci 0000:04:00.1: enabling device (0000 -> 0002)
Aug  8 01:58:35 debian goes.vnetd[26823]: SetSpeed    eth-1-1, laneMask=   1, firstLaneMask=   1 Nlanes=1
Aug  8 01:58:35 debian goes.vnetd[26823]:   Set portMode=0
Aug  8 01:58:35 debian goes.vnetd[26823]:   eth-1-1 Set FEC, Cl91=false, CL74=true, FecEnable=false
Aug  8 01:58:35 debian goes.vnetd[26823]:   eth-1-1 Set speed = 1e+10 media=optics
Aug  8 01:58:35 debian goes.vnetd[26823]:   eth-1-1 Set PLL mult = 4
Aug  8 01:58:35 debian goes.vnetd[26823]:   eth-1-2 Set FEC, Cl91=false, CL74=true, FecEnable=false
Aug  8 01:58:35 debian goes.vnetd[26823]:   eth-1-2 Set speed = 0 media=optics
Aug  8 01:58:35 debian goes.vnetd[26823]: eventHandler: panic vnet: unsupported speed/lane mask combination 0.000000e+00 0x2
Aug  8 01:58:35 debian goes.vnetd[26823]: panic: vnet: unsupported speed/lane mask combination 0.000000e+00 0x2
Aug  8 01:58:35 debian goes.vnetd[26823]: goroutine 135 [running]:
Aug  8 01:58:35 debian goes.vnetd[26823]: runtime/debug.Stack(0xc33fc0, 0xc423654390, 0xc422939628)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /usr/lib/go-1.9/src/runtime/debug/stack.go:24 +0xa7
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler.func1(0xc420176418, 0xc420176970)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:189 +0x1c9
Aug  8 01:58:35 debian goes.vnetd[26823]: panic(0xc33fc0, 0xc423654370)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/fe1/internal/phy.(*HundredGig).SetSpeed(0xc420fd2650, 0x19aabe0, 0xc420fdb400, 0x4202a05f20000000, 0x0)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/phy/hundred_gig.go:803 +0x11d5
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/fe1/internal/port.(*PortBlock).setPhySpeed(0xc420fd0a20, 0x19aabe0, 0xc420fdb400)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/port/port.go:212 +0xd4
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/fe1/internal/port.(*PortBlock).SetPortEnable(0xc420fd0a20, 0x19aabe0, 0xc420fdb400, 0xc42024e501)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/port/port.go:272 +0x17b
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/fe1/internal/fe1a.(*Port).port_up_down(0xc420fdb400, 0xc420b32000, 0x500000001)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/fe1a/port_init.go:902 +0x62
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).swIfAdminUpDown(0xc420b32000, 0xc420176418, 0x100000005, 0x0, 0x0)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/fe1a/l3_interface.go:732 +0x120
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).(github.com/platinasystems/fe1/internal/fe1a.swIfAdminUpDown)-fm(0xc420176418, 0x100000005, 0xc420a62f70, 0xc4233a1cb0)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/fe1/internal/fe1a/l3.go:30 +0x45
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/go/vnet.(*SwIf).SetAdminUp(0xc4236dec50, 0xc420176418, 0xc4207a3001, 0x5, 0x100000005)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/interface.go:344 +0xca
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/go/vnet.Si.SetAdminUp(0xc400000005, 0xc420176418, 0x100000001, 0x1a0cf00, 0x0)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/interface.go:354 +0x62
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc423066940)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:465 +0x88f
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/go/elib/loop.(*nodeEvent).do(0xc4230669c0)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:158 +0x98
Aug  8 01:58:35 debian goes.vnetd[26823]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420176418, 0x199b380, 0xc420176968)
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:228 +0xa3
Aug  8 01:58:35 debian goes.vnetd[26823]: created by github.com/platinasystems/go/elib/loop.(*Node).maybeStartEventHandler.func1
Aug  8 01:58:35 debian goes.vnetd[26823]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:389 +0x271
Aug  8 01:58:35 debian kernel: ixgbe 0000:03:00.1 eth2: NIC Link is Up 10 Gbps, Flow Control: RX/TX
Aug  8 01:58:36 debian kernel: ixgbe 0000:03:00.0 eth1: NIC Link is Up 10 Gbps, Flow Control: RX/TX
```

**Comment by sandeep-dutta** [comment]
Issue is not valid with the current goes build since we use ethtool to set speed, media & fec parameters. Hence, closing the bug.
