### ISSUE TITLE
Not able to create GRE tunnel between invader to invader

### ISSUE THREAD

**Issue by jignesh045** [platinasystems/go#134]
Issue Statement: Not able to create GRE tunnel between invader to invader

Environment: Inv45 & Inv43 with below build

```
root@invader45:~# goes version
github.com/platinasystems/go: v0.41-362-g3bc4ae90
github.com/platinasystems/fe1: v0.2-532-g4f773aa
github.com/platinasystems/firmware-fe1a: v0.2
root@invader45:~#
root@invader45:~# goes hget platina-mk1 packages | grep version:
    version: 3bc4ae907d7a263cc28b019885980d386492788d
    version: 4f773aa5e253915d82f866571b2f21476116421a
    version: 60f39141fbbf78ddb2260dba74c68f2789374f18
root@invader45:~#
root@invader45:~# dpkg --list |grep kernel
ii  kmod                           18-3                             amd64        tools for managing Linux kernel modules
ii  libdrm2:amd64                  2.4.58-2                         amd64        Userspace interface to kernel DRM services -- runtime
ii  linux-image-4.13.0-platina-mk1 4.13-134-g39fbcf8c984f           amd64        Linux kernel, version 4.13.0-platina-mk1
ii  rsyslog                        8.4.2-1+deb8u2                   amd64        reliable system and kernel logging daemon
root@invader45:~#
```

Steps: 

1. Create GRE tunnel using below command

On Inv45:

```
root@invader45:/home/jignesh# ip link add tun0 type gre external
root@invader45:/home/jignesh#
root@invader45:/home/jignesh# ip link set tun0 up
root@invader45:/home/jignesh#
root@invader45:/home/jignesh# ip add add 50.0.0.1/30 dev tun0
root@invader45:/home/jignesh#
root@invader45:/home/jignesh# ip route add 50.0.0.2/32 encap ip dst 192.168.101.131 ttl 10 dev tun0
root@invader45:/home/jignesh#
```

On Inv43:

```
root@invader43:/home/jignesh# ip link add tun0 type gre external
root@invader43:/home/jignesh#
root@invader43:/home/jignesh# ip link set tun0 up
root@invader43:/home/jignesh#
root@invader43:/home/jignesh# ip add add 50.0.0.2/30 dev tun0
root@invader43:/home/jignesh#
root@invader43:/home/jignesh# ip route add 50.0.0.1/32 encap ip dst 192.168.101.121 ttl 10 dev tun0
root@invader43:/home/jignesh#
```

2. Observe the GoES status after some time.

```
root@invader43:/# goes status
GOES status
======================
  Mode            - SRIOV
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - Not OK
status: vnetd daemon not responding
root@invader43:/#
```

```
root@invader45:~# goes status
GOES status
======================
  Mode            - SRIOV
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - Not OK
status: vnetd daemon not responding
root@invader45:~#
```

3. Observed /var/log/syslog

On Inv43:

```
Aug 17 04:56:38 debian kernel: gre: GRE over IPv4 demultiplexor driver
Aug 17 04:56:38 debian kernel: ip_gre: GRE over IPv4 tunneling driver
Aug 17 04:56:55 debian goes.vnetd[27395]: eventHandler: panic vnet: runtime error: invalid memory address or nil pointer dereference
Aug 17 04:56:55 debian goes.vnetd[27395]: panic: vnet: runtime error: invalid memory address or nil pointer dereference
Aug 17 04:56:55 debian goes.vnetd[27395]: goroutine 53 [running]:
Aug 17 04:56:55 debian goes.vnetd[27395]: runtime/debug.Stack(0xc31e60, 0xc422326060, 0xc420a2daf0)
Aug 17 04:56:55 debian goes.vnetd[27395]:         /usr/lib/go-1.9/src/runtime/debug/stack.go:24 +0xa7
Aug 17 04:56:55 debian goes.vnetd[27395]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler.func1(0xc420174418, 0xc420174970)
Aug 17 04:56:55 debian goes.vnetd[27395]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:189 +0x1c9
Aug 17 04:56:55 debian goes.vnetd[27395]: panic(0xc4fdc0, 0x183ae10)
Aug 17 04:56:55 debian goes.vnetd[27395]:         /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
Aug 17 04:56:55 debian goes.vnetd[27395]: github.com/platinasystems/go/vnet/unix.(*net_namespace).msg_for_vnet_interface(0xc420175090, 0x19a76c0, 0xc4201904e0, 0xc420a2de70)
Aug 17 04:56:55 debian goes.vnetd[27395]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:195 +0x266
Aug 17 04:56:55 debian goes.vnetd[27395]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc423296140)
Aug 17 04:56:55 debian goes.vnetd[27395]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:438 +0xf7
Aug 17 04:56:55 debian goes.vnetd[27395]: github.com/platinasystems/go/elib/loop.(*nodeEvent).do(0xc423296440)
Aug 17 04:56:55 debian goes.vnetd[27395]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:158 +0x98
Aug 17 04:56:55 debian goes.vnetd[27395]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420174418, 0x1997fe0, 0xc420174968)
Aug 17 04:56:55 debian goes.vnetd[27395]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:228 +0xa3
Aug 17 04:56:55 debian goes.vnetd[27395]: created by github.com/platinasystems/go/elib/loop.(*Node).maybeStartEventHandler.func1
Aug 17 04:56:55 debian goes.vnetd[27395]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:389 +0x271
Aug 17 04:58:02 debian ntpd[2013]: Listen normally on 941 tun0 50.0.0.2 UDP 123
Aug 17 04:58:02 debian ntpd[2013]: Listen normally on 942 tun0 fe80::cfa2:2010:9bdf:c1d6 UDP 123
Aug 17 04:58:02 debian ntpd[2013]: peers refreshed
Aug 17 05:17:01 debian CRON[27543]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
```

On Inv45:

```
Aug 17 04:55:10 debian goes.vnetd[19927]: eventHandler: panic vnet: runtime error: invalid memory address or nil pointer dereference
Aug 17 04:55:10 debian goes.vnetd[19927]: panic: vnet: runtime error: invalid memory address or nil pointer dereference
Aug 17 04:55:10 debian goes.vnetd[19927]: goroutine 38 [running]:
Aug 17 04:55:10 debian goes.vnetd[19927]: runtime/debug.Stack(0xc31e60, 0xc423b941c0, 0xc421d6daf0)
Aug 17 04:55:10 debian goes.vnetd[19927]:         /usr/lib/go-1.9/src/runtime/debug/stack.go:24 +0xa7
Aug 17 04:55:10 debian goes.vnetd[19927]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler.func1(0xc420182418, 0xc420182970)
Aug 17 04:55:10 debian goes.vnetd[19927]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:189 +0x1c9
Aug 17 04:55:10 debian goes.vnetd[19927]: panic(0xc4fdc0, 0x183ae10)
Aug 17 04:55:10 debian goes.vnetd[19927]:         /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
Aug 17 04:55:10 debian goes.vnetd[19927]: github.com/platinasystems/go/vnet/unix.(*net_namespace).msg_for_vnet_interface(0xc420183090, 0x19a76c0, 0xc420074340, 0xc421d6de70)
Aug 17 04:55:10 debian goes.vnetd[19927]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:195 +0x266
Aug 17 04:55:10 debian goes.vnetd[19927]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc423b96b00)
Aug 17 04:55:10 debian goes.vnetd[19927]:         /home/arthur/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:438 +0xf7
Aug 17 04:55:10 debian goes.vnetd[19927]: github.com/platinasystems/go/elib/loop.(*nodeEvent).do(0xc423b96b40)
Aug 17 04:55:10 debian goes.vnetd[19927]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:158 +0x98
Aug 17 04:55:10 debian goes.vnetd[19927]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420182418, 0x1997fe0, 0xc420182968)
Aug 17 04:55:10 debian goes.vnetd[19927]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:228 +0xa3
Aug 17 04:55:10 debian goes.vnetd[19927]: created by github.com/platinasystems/go/elib/loop.(*Node).maybeStartEventHandler.func1
Aug 17 04:55:10 debian goes.vnetd[19927]:         /home/arthur/gopath/src/github.com/platinasystems/go/elib/loop/event.go:389 +0x271
Aug 17 05:17:01 debian CRON[20118]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
```

4. Delete the GRE interface

```
root@invader45:~# ip link del tun0 type gre external
root@invader45:~#
```

5. restart goes & check goes status

```
root@invader45:~# goes restart
restart: stop: failed to kill /proc/19927/exe
root@invader45:~#

```
```
root@invader45:~# goes status
GOES status
======================
  Mode            - SRIOV
  PCI             - OK
  Check daemons   - Not OK
status: redisd daemon not running
uptimed daemon not running
bootd daemon not running
root@invader45:~#
```

6. rebooted device in order to recover goes status

**Comment by stigt** [comment]
I don't think we expect this feature to work at this point.
