### ISSUE TITLE
vnet crash in ForEachUnresolved after UnsetBridge

### ISSUE THREAD

**Issue by rondv** [platinasystems/go#152]
local build of v1.2.0-rc0
 
goes test stopped while running Test/vlan/slice, then ran br_ping.sh ns_test which likely had conflicting config.  Result was the crash shown below

Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/unix.(*net_namespace).addDelMk1Interface() ns ns1 delete ifname tb1 ifindex 100000 address [246 80 1 169 6 118] devtype 131 iflinkindex 100000 vlanid 3002
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/unix.(*net_namespace).addDelMk1Interface() addDelMk1Interface: Del xeth.XETH_DEVTYPE_LINUX_BRIDGE tb1 3002
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet.(*Vnet).addDelSwInterface() si 4294967295.152 SwIfKindInvalid 0 , del true
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).vlanBridgeAddDel() FromVnet br[152] stag 3002, add false
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).vlanPortRemove() rx
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).vlanPortRemove() tx , ubm
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).vlanDestroy() 3002
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/ethernet.UnsetBridge() delete bridge tb1, stag 3002
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet.UnsetPort() tb1
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet.UnsetPort() delete port tb1, ifindex 100000
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/unix.(*fdbEvent).EventAction() kind: ifinfo
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/unix.ProcessInterfaceInfo() 3 tb12 120000 131
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/unix.ProcessInterfaceInfo() dynamic ifinfo ns12 tb12 ns12
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/unix.ProcessInterfaceInfo() tb12 unreg vlan ns12
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/unix.(*net_namespace).addDelMk1Interface() ns ns12 delete ifname tb12 ifindex 120000 address [94 92 14 150 228 208] devtype 131 iflinkindex 120000 vlanid 3003
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/unix.(*net_namespace).addDelMk1Interface() addDelMk1Interface: Del xeth.XETH_DEVTYPE_LINUX_BRIDGE tb12 3003
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet.(*Vnet).addDelSwInterface() si 4294967295.154 SwIfKindInvalid 0 , del true
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).vlanBridgeAddDel() FromVnet br[154] stag 3003, add false
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).vlanPortRemove() rx
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).vlanPortRemove() tx , ubm
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).vlanDestroy() 3003
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/ethernet.UnsetBridge() delete bridge tb12, stag 3003
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet.UnsetPort() tb12
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet.UnsetPort() delete port tb12, ifindex 120000
Jan 23 19:27:50 invader4 goes.vnetd[21342]: eventHandler: panic vnet: runtime error: invalid memory address or nil pointer dereference
Jan 23 19:27:50 invader4 goes.vnetd[21342]: panic: vnet: runtime error: invalid memory address or nil pointer dereference
Jan 23 19:27:50 invader4 goes.vnetd[21342]: goroutine 73 [running]:
Jan 23 19:27:50 invader4 goes.vnetd[21342]: runtime/debug.Stack(0xaee9c0, 0xc001ae2530, 0xc003a1bb50)
Jan 23 19:27:50 invader4 goes.vnetd[21342]: /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/elib/loop.(*Loop).eventHandler.func1(0xc000218000, 0xc000218550)
Jan 23 19:27:50 invader4 goes.vnetd[21342]: /home/rtaylor/gopath/src/github.com/platinasystems/elib/loop/event.go:189 +0x190
Jan 23 19:27:50 invader4 goes.vnetd[21342]: panic(0xb040a0, 0x16141c0)
Jan 23 19:27:50 invader4 goes.vnetd[21342]: /usr/local/go/src/runtime/panic.go:513 +0x1b9
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/vnet/ip4.(*Main).ForeachUnresolved(0xc000468000, 0xc003a1be78)
Jan 23 19:27:50 invader4 goes.vnetd[21342]: /home/rtaylor/gopath/src/github.com/platinasystems/vnet/ip4/fib.go:403 +0x170
Jan 23 19:27:50 invader4 goes.vnetd[21342]: main.(*unresolvedArper).EventAction(0xc000218c10)
Jan 23 19:27:50 invader4 goes.vnetd[21342]: /home/rtaylor/gopath/src/github.com/platinasystems/vnet-platina-mk1/unresolvedArper.go:35 +0xab
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/elib/loop.(*nodeEvent).do(0xc00145ac40)
Jan 23 19:27:50 invader4 goes.vnetd[21342]: /home/rtaylor/gopath/src/github.com/platinasystems/elib/loop/event.go:158 +0x99
Jan 23 19:27:50 invader4 goes.vnetd[21342]: github.com/platinasystems/elib/loop.(*Loop).eventHandler(0xc000218000, 0xdd60c0, 0xc000218548)
Jan 23 19:27:50 invader4 goes.vnetd[21342]: /home/rtaylor/gopath/src/github.com/platinasystems/elib/loop/event.go:228 +0xa3
Jan 23 19:27:50 invader4 goes.vnetd[21342]: created by github.com/platinasystems/elib/loop.(*Node).maybeStartEventHandler.func1
Jan 23 19:27:50 invader4 goes.vnetd[21342]: /home/rtaylor/gopath/src/github.com/platinasystems/elib/loop/event.go:389 +0x228
Jan 23 19:27:51 invader4 kernel: 8021q: adding VLAN 0 to HW filter on device xeth31
Jan 23 19:27:51 invader4 kernel: device xeth31 entered promiscuous mode
Jan 23 19:27:51 invader4 kernel: IPv6: ADDRCONF(NETDEV_UP): xeth31.30: link is not ready
Jan 23 19:27:51 invader4 kernel: IPv6: ADDRCONF(NETDEV_UP): tb3: link is not ready
Jan 23 19:27:51 invader4 kernel: IPv6: ADDRCONF(NETDEV_UP): xeth12: link is not ready
Jan 23 19:27:51 invader4 kernel: 8021q: adding VLAN 0 to HW filter on device xeth12
Jan 23 19:27:51 invader4 kernel: IPv6: ADDRCONF(NETDEV_UP): xeth12.10: link is not ready

**Comment by rondv** [comment]
haven't seen this in recent builds
