### ISSUE TITLE
Any vnet show cmd crashes vnet

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#22]
sudo goes restart
ps -e f
sudo goes vnet show ip fib
  [takes a long time, ~5s]
ps -e f
  [vnet is dead]
syslog:
  "runtime error: index out of range: goroutine 45 [running]"

Version:

```
commit c332849fbd55d6ef85c5e89c8803778622456916
Author: Mark Pleso <mpleso@platinasystems.com>
Date:   Sat Feb 18 23:47:35 2017 -0800

    Changed mknod permissions to octal

    Signed-off-by: Mark Pleso <mpleso@platinasystems.com>
```

Details:

```
donn@invader8:~/workspace/go/src/github.com/platinasystems/go$ sudo goes restart

donn@invader8:~/workspace/go/src/github.com/platinasystems/go$ ps -e f
  PID TTY      STAT   TIME COMMAND
    2 ?        S      0:00 [kthreadd]
    3 ?        S      0:57  \_ [ksoftirqd/0]
    5 ?        S<     0:00  \_ [kworker/0:0H]
<...>
18958 ?        Ssl    0:00 goes-daemons
18966 ?        Sl     0:00  \_ redisd
19002 ?        Sl     0:00  \_ vnetd
19003 ?        Sl     0:00  \_ uptimed
19007 ?        Sl     0:00  \_ nld

donn@invader8:~/workspace/go/src/github.com/platinasystems/go$ sudo goes vnet sho
w ip fib
vnet: /run/goes/socks/vnet: timeout
donn@invader8:~/workspace/go/src/github.com/platinasystems/go$

donn@invader8:~/workspace/go/src/github.com/platinasystems/go$ ps -e f
  PID TTY      STAT   TIME COMMAND
    2 ?        S      0:00 [kthreadd]
    3 ?        S      0:57  \_ [ksoftirqd/0]
    5 ?        S<     0:00  \_ [kworker/0:0H]
<...>
18958 ?        Ssl    0:00 goes-daemons
18966 ?        Sl     0:00  \_ redisd
19003 ?        Sl     0:00  \_ uptimed
19007 ?        Sl     0:00  \_ nld
donn@invader8:~/workspace/go/src/github.com/platinasystems/go$

syslog:


Feb 21 14:40:32 invader8 goes.redisd[18966]: listen: /run/goes/socks/redisd
Feb 21 14:40:32 invader8 goes.redisd[18966]: listen: [7.7.7.7%lo]:6379
Feb 21 14:40:32 invader8 goes.redisd[18966]: listen: [::1%lo]:6379
Feb 21 14:40:32 invader8 goes.redisd[18966]: listen: [192.168.101.128%eth0]:6379
Feb 21 14:40:32 invader8 goes.redisd[18966]: listen: [fe80::46:8aff:fe00:53e%eth0
]:6379
Feb 21 14:40:49 invader8 goes.vnetd[19002]: runtime error: index out of range: go
routine 45 [running]:
Feb 21 14:40:49 invader8 goes.vnetd[19002]: runtime/debug.Stack(0x0, 0x0, 0x0)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /usr/local/go/src/runtime/deb
ug/stack.go:24 +0x80
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/elib/loo
p.(*Loop).doEvent.func1(0xc820184000)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/sr
c/github.com/platinasystems/go/elib/loop/event.go:128 +0xa2
Feb 21 14:40:49 invader8 goes.vnetd[19002]: panic(0xda3fa0, 0xc82000a030)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /usr/local/go/src/runtime/pan
ic.go:443 +0x4e9
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/vnet/dev
ices/ethernet/switch/fe1/internal/fe1a.(*fe1a).ip4_fib_add_del(0xc820230000, 0xc8
00000000, 0xc8213167d8, 0x2)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/sr
c/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/fib
.go:286 +0xf63
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/vnet/dev
ices/ethernet/switch/fe1/internal/fe1a.(*fe1a).(github.com/platinasystems/go/vnet
/devices/ethernet/switch/fe1/internal/fe1a.ip4_fib_add_del)-fm(0xc800000000, 0xc8
213167d8, 0x2)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/sr
c/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/fib
.go:49 +0x4c
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDel(0xc8204fa160, 0xc8201f8000, 0xc8213167d8, 0x2, 0x7f01fffffffe)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:217 +0x32f
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/vnet/ip4.(*Main).addDelRoute(0xc8201f8000, 0xc82130f940, 0x200000000, 0x0, 0xdbd4c0, 0x0, 0x0)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:367 +0x1cf
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.addDelRoute)-fm(0xc82130f940, 0x200000000, 0x0, 0xc8201a59f8, 0x0, 0x0)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/package.go:43 +0x51
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/vnet/unix.(*Main).ip4IfaddrMsg(0xc8201ce480, 0xc820098420, 0x0, 0x0)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:386 +0x3d4
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc820504b10)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:288 +0x2a1
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc82088a000)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x135
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc820184000, 0xc82088a000)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x48
Feb 21 14:40:49 invader8 goes.vnetd[19002]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc820184000, 0x7f1a70120028, 0xc820184548)
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x81
Feb 21 14:40:49 invader8 goes.vnetd[19002]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Feb 21 14:40:49 invader8 goes.vnetd[19002]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x120
```

**Comment by dlobete** [comment]
Must be some prerequisite before the restart?

I can't reproduce with 5 tries:

root@invader5:/home/dlobete/src/github.com/platinasystems/go# goes restart
root@invader5:/home/dlobete/src/github.com/platinasystems/go# goes vnet
show ip fib
 Table                   Destination           Adjacency
     0                   20.0.0.0/24  3: glean eth-30-0
     0                   20.0.0.5/32  4: local eth-30-0

**Comment by donnlee** [comment]
That's interesting. No, I don't do anything special (that I'm aware of) before 'goes restart'.   I did 'goes install' of an older binary and it worked without any problems.

**Comment by dlobete** [comment]
I'm at top-of-tree right now.
Don.

**Comment by dlobete** [comment]
What's the output of "ip route" ?
Don.

**Comment by donnlee** [comment]
In fact 'goes install' is giving me what looks like the same thing:

```
Feb 21 15:26:35 invader8 goes.vnetd[27025]: runtime error: index out of range: go
routine 51 [running]:
Feb 21 15:26:35 invader8 goes.vnetd[27025]: runtime/debug.Stack(0xc4201bb830, 0xa
3fc20, 0xc42000c0a0)
Feb 21 15:26:35 invader8 goes.vnetd[27025]:         /usr/local/go/src/runtime/deb
ug/stack.go:24 +0x79
Feb 21 15:26:35 invader8 goes.vnetd[27025]: github.com/platinasystems/go/elib/loo
p.(*Loop).doEvent.func1(0xc420192000)
Feb 21 15:26:35 invader8 goes.vnetd[27025]:         /home/donn/workspace/go/src/g
ithub.com/platinasystems/go/elib/loop/event.go:128 +0x91
Feb 21 15:26:35 invader8 goes.vnetd[27025]: panic(0xa3fc20, 0xc42000c0a0)
Feb 21 15:26:35 invader8 goes.vnetd[27025]:         /usr/local/go/src/runtime/pan
ic.go:458 +0x243
Feb 21 15:26:35 invader8 goes.vnetd[27025]: github.com/platinasystems/go/vnet/dev
ices/ethernet/switch/fe1/internal/fe1a.(*fe1a).ip4_fib_add_del(0xc42021c000, 0xc4
00000000, 0xc4212d6bf8, 0x2)
Feb 21 15:26:35 invader8 goes.vnetd[27025]:         /home/donn/workspace/go/src/g
ithub.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/fib.go
:286 +0xa61
Feb 21 15:26:35 invader8 goes.vnetd[27025]: github.com/platinasystems/go/vnet/dev
ices/ethernet/switch/fe1/internal/fe1a.(*fe1a).(github.com/platinasystems/go/vnet
/devices/ethernet/switch/fe1/internal/fe1a.ip4_fib_add_del)-fm(0xc400000000, 0xc4
212d6bf8, 0x2)
Feb 21 15:26:35 invader8 goes.vnetd[27025]:         /home/donn/workspace/go/src/g
ithub.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/fib.go
:49 +0x56
Feb 21 15:26:35 invader8 goes.vnetd[27025]: github.com/platinasystems/go/vnet/ip4
.(*Fib).addDel(0xc4204b4160, 0xc42018e700, 0xc4212d6bf8, 0x100000000000002, 0x0)
<...>
```

**Comment by donnlee** [comment]
i8's 'ip route'  is below.  Nothing special for many weeks.
I did add the default route today (I remove the default route when I do punt path testing).

donn@invader8:~/workspace/go/src/github.com/platinasystems/go$ ip ro
default via 192.168.101.2 dev eth0
10.2.0.0/16 dev flannel.1  proto kernel  scope link  src 10.2.65.0
10.2.65.0/24 dev docker0  proto kernel  scope link  src 10.2.65.1
104.210.2.228 via 192.168.101.2 dev eth0
172.16.2.0/23 via 192.168.101.2 dev eth0
172.17.0.0/16 dev br-131bf7797fb8  proto kernel  scope link  src 172.17.0.1
172.19.0.0/16 dev br-e7353579d7a2  proto kernel  scope link  src 172.19.0.1
192.168.101.0/24 dev eth0  proto kernel  scope link  src 192.168.101.128
192.227.159.46 via 192.168.101.2 dev eth0
donn@invader8:~/workspace/go/src/github.com/platinasystems/go$

**Comment by dlobete** [comment]
You updated fe1 area too ?
Don.

**Comment by donnlee** [comment]
Yes, I refreshed fe1 like so:

donn@invader8:~/workspace/go/src/github.com/platinasystems/go$ rm -rf vnet/device
s/ethernet/switch/fe1/
donn@invader8:~/workspace/go/src/github.com/platinasystems/go$ git clone git@github.com:platinasystems/fe1 vnet/devices/ethernet/switch/fe1
Cloning into 'vnet/devices/ethernet/switch/fe1'...
Enter passphrase for key '/home/donn/.ssh/id_rsa':
remote: Counting objects: 274, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 274 (delta 6), reused 0 (delta 0), pack-reused 259
Receiving objects: 100% (274/274), 314.04 KiB | 158.00 KiB/s, done.
Resolving deltas: 100% (121/121), done.
Checking connectivity... done.
donn@invader8:~/workspace/go/src/github.com/platinasystems/go$

**Comment by donnlee** [comment]
Possibly related to (same root cause) of #23

**Comment by donnlee** [comment]
Fixed.  See #23 for re-test output.
Though be aware of #26
