### ISSUE TITLE
index out of range: go/vnet/ip4.showIpFib

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#25]
i8 had a gobgp session established with another gobgp router (pktgen/i14).
i14 sent 4K bgp routes to i8.
Not all routes were installed.
Then i did 'vnet show ip fib' and got a panic:

```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/punt_path$ gobgp neighbor
Peer             AS  Up/Down State       |#Advertised Received Accepted
10.0.29.14    65201 00:00:26 Establ      |          8      425      425
192.168.155.2 65202 00:00:29 Establ      |        431        0        0
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/punt_path$ gobgp neighbor
Peer             AS  Up/Down State       |#Advertised Received Accepted
10.0.29.14    65201 00:00:28 Establ      |          8      425      425
192.168.155.2 65202 00:00:31 Establ      |        431        0        0
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/punt_path$ goes vnet sho ip fib
 Table                   Destination           Adjacency
show ip fib: runtime error: index out of range `': goroutine 51 [running]:
runtime/debug.Stack(0xc4201b7bc0, 0xb79671, 0xb)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/platinasystems/go/elib/cli.(*Main).ExecInput.func1(0xc420032df8, 0x12875a0, 0xc4201b7bc0, 0
xc42019a270)
        /home/dlobete/src/github.com/platinasystems/go/elib/cli/cli.go:219 +0x9c
panic(0xa79ce0, 0xc42000c0a0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).adj_get_counter(0x
c420224000, 0xc420196768, 0x2, 0xc4211af4a0)
        /home/dlobete/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/
fib.go:170 +0xdb
github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).(github.com/platin
asystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.adj_get_counter)-fm(0xc420196768, 0x2, 0xc4
211af4a0)
        /home/dlobete/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/
fib.go:51 +0x46
github.com/platinasystems/go/vnet/ip.(*Main).CallAdjGetCounterHooks(0xc420196768, 0x2, 0xc4211af4a0)
        /home/dlobete/src/github.com/platinasystems/go/vnet/ip/adjacency.go:629 +0x78
github.com/platinasystems/go/vnet/ip.(*Main).ForeachAdjCounter(0xc420196768, 0xc400000002, 0xc4211af4a
0)
        /home/dlobete/src/github.com/platinasystems/go/vnet/ip/adjacency.go:680 +0x1a2
github.com/platinasystems/go/vnet/ip4.(*Main).showIpFib(0xc420196700, 0x12875a0, 0xc4201b7bc0, 0x7fd0e
045e938, 0xc4200c4780, 0xc42019a270, 0x42c993, 0xc420032d40)
        /home/dlobete/src/github.com/platinasystems/go/vnet/ip4/cli.go:86 +0x8b5
github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.showIpFib)-fm(0x1
2875a0, 0xc4201b7bc0, 0x7fd0e045e938, 0xc4200c4780, 0xc42019a270, 0xc420032d00, 0x7fd0e045e938)
        /home/dlobete/src/github.com/platinasystems/go/vnet/ip4/cli.go:110 +0x5c
github.com/platinasystems/go/elib/cli.(*Command).CliAction(0xc4201b7bc0, 0x7fd0e045e938, 0xc4200c4780,
 0xc42019a270, 0xc4200c4780, 0xc42019a270)
        /home/dlobete/src/github.com/platinasystems/go/elib/cli/cli.go:53 +0x59
github.com/platinasystems/go/elib/cli.(*Main).ExecInput(0xc42019a270, 0x1283160, 0xc4200c4780, 0xc4201
9a270, 0x0, 0x0)
        /home/dlobete/src/github.com/platinasystems/go/elib/cli/cli.go:222 +0x134
github.com/platinasystems/go/elib/cli.(*Main).Exec(0xc42019a270, 0x1283160, 0xc4200c4780, 0x1284ea0, 0
xc423c3d940, 0xa, 0xc420476000)
        /home/dlobete/src/github.com/platinasystems/go/elib/cli/cli.go:230 +0x82
github.com/platinasystems/go/elib/cli.(*File).RxReady(0xc4200c4780, 0xc42047c748, 0xc42047c758)
        /home/dlobete/src/github.com/platinasystems/go/elib/cli/file.go:61 +0x1dc
github.com/platinasystems/go/elib/loop.(*fileEvent).EventAction(0xc4212c6700)
        /home/dlobete/src/github.com/platinasystems/go/elib/loop/cli.go:38 +0x33
github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc42110e840)
        /home/dlobete/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc42019a000, 0xc42110e840)
        /home/dlobete/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc42019a000, 0x12876a0, 0xc42019a138)
        /home/dlobete/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
        /home/dlobete/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/punt_path$
```

```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/punt_path$ /usr/bin/goes version
1df40b36f56a005cb48fe61249c0513f5b440087
```

**Comment by donnlee** [comment]
vnet did not die, but I get the same panic output every time I do 'vnet sh ip fib'.

```
32535 ?        Ssl    0:00 goes-daemons
32544 ?        Sl     0:00  \_ redisd
32574 ?        Sl     0:04  \_ i2cd
32575 ?        Sl     0:03  \_ vnetd
32579 ?        Sl     0:00  \_ uptimed
32583 ?        Sl     0:00  \_ telnetd
32591 ?        Sl     0:00  \_ qsfpio
32603 ?        Sl     0:01  \_ nld
32627 ?        Sl     0:00  \_ qsfp
```

**Comment by donnlee** [comment]
May be related to #18

**Comment by donnlee** [comment]
Closing per @fszyang (upon closing #18)
