### ISSUE TITLE
control-c during "vnet show ip fib" can crash vnet

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#28]
I'm using bgp_simple to inject over 15000 routes.  I issued the show command and did a control-c since it was a lot of output.  

stig@invader1:~/bin$ sudo goes vnet show ip fib | wc -l
15504

stig@invader1:~/bin$ sudo goes vnet show ip fib | more
 Table                   Destination           Adjacency
     0                    1.0.0.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                    1.0.4.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                    1.0.5.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                    1.0.6.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                    1.0.7.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                   1.0.38.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                   1.0.64.0/18  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.128.0/17  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.128.0/18  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.128.0/19  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.128.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.129.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.131.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.139.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.142.0/24  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.160.0/19  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.160.0/21  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.192.0/18  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.192.0/19  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.192.0/21  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
     0                  1.0.208.0/22  6: rewrite eth-0-0 IP4: 02:46:8a:00:02:a2 -> 02:46:8a:00:01:96
^c

stig@invader1:~/bin$ sudo goes vnet show ip fib |more
vnet: dial unix /run/goes/socks/vnet: connect: connection refused

Mar 10 15:02:48 invader1 goes.vnetd[4594]: panic: unix:/run/goes/socks/vnet -> unix:@
Mar 10 15:02:48 invader1 goes.vnetd[4594]: 
Mar 10 15:02:48 invader1 goes.vnetd[4594]: goroutine 22 [running]:
Mar 10 15:02:48 invader1 goes.vnetd[4594]: panic(0xed3a80, 0xc820084d88)
Mar 10 15:02:48 invader1 goes.vnetd[4594]:         /usr/local/go/src/runtime/panic.go:464 +0x3e6
Mar 10 15:02:48 invader1 goes.vnetd[4594]: github.com/platinasystems/go/elib/socket.(*socket).ErrorReady(0xc820084d88, 0x0, 0x0)
Mar 10 15:02:48 invader1 goes.vnetd[4594]:         /home/stig/go/src/github.com/platinasystems/go/elib/socket/socket.go:221 +0x31
Mar 10 15:02:48 invader1 goes.vnetd[4594]: github.com/platinasystems/go/elib/cli.(*File).ErrorReady(0xc820be5338, 0x0, 0x0)
Mar 10 15:02:48 invader1 goes.vnetd[4594]:         <autogenerated>:59 +0x5c
Mar 10 15:02:48 invader1 goes.vnetd[4594]: github.com/platinasystems/go/elib/iomux.(*Mux).do(0x19078e0, 0xc8236272f0)
Mar 10 15:02:48 invader1 goes.vnetd[4594]:         /home/stig/go/src/github.com/platinasystems/go/elib/iomux/epoll.go:153 +0x329
Mar 10 15:02:48 invader1 goes.vnetd[4594]: github.com/platinasystems/go/elib/iomux.(*Mux).EventPoll(0x19078e0)
Mar 10 15:02:48 invader1 goes.vnetd[4594]:         /home/stig/go/src/github.com/platinasystems/go/elib/iomux/epoll.go:166 +0x24b
Mar 10 15:02:48 invader1 goes.vnetd[4594]: github.com/platinasystems/go/elib/loop.(*eventLoop).eventPoller(0xc820186370, 0x7f77237cb280, 0x19078e0)
Mar 10 15:02:48 invader1 goes.vnetd[4594]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:158 +0x27
Mar 10 15:02:48 invader1 goes.vnetd[4594]: created by github.com/platinasystems/go/elib/loop.(*eventLoop).startPoller
Mar 10 15:02:48 invader1 goes.vnetd[4594]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:161 +0x49
Mar 10 15:02:50 invader1 goes.vnetd[4594]: exit status 2

**Comment by stigt** [comment]
in go/elib/socket/socket.go

func (s *socket) ErrorReady() (err error) {
	panic(s)
}

**Comment by stigt** [comment]
Fixed with following commit:https://github.com/platinasystems/go/commit/7912258f3ba5c9937db099b2a27c439e228a762c
