### ISSUE TITLE
panic on "goes stop"

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#31]
This might be lower priority since it's happening on a goes stop and so far only reproducible on invader24 which has traffic flowing.

- Run 1 iteration of torture script:

root@invader24:/home/stig# ./torture 1
Wed Mar  1 18:18:12 PST 2017
interation 1
stopping
starting
vnet.ready = true
reading vnet counters
val = 738
Add route - OK
Del route - OK
Done

- Check the fib on the interface with static route added:

root@invader24:/home/stig# goes vnet show ip fib | grep eth-1-1
     0                    1.1.1.0/24  579: glean eth-1-1
     0                    1.1.1.1/32  580: local eth-1-1
     0                    1.1.1.2/32  581: rewrite eth-1-1 IP4: 6c:ec:5a:07:d1:a0 -> 00:01:02:03:04:05

- Stop goes, syslog shows:

Mar  1 18:29:35 invader24 goes.vnetd[29345]: panic in addDelReplace 1.1.1.1/24 4294967294 true
Mar  1 18:29:35 invader24 goes.vnetd[29345]: addDelReplace: goroutine 36 [running]:
Mar  1 18:29:35 invader24 goes.vnetd[29345]: runtime/debug.Stack(0x0, 0x0, 0x0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x80
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc82018e000)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:128 +0xa2
Mar  1 18:29:35 invader24 goes.vnetd[29345]: panic(0xbaa2e0, 0xc82012dfe0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /usr/local/go/src/runtime/panic.go:426 +0x4e9
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDelReplace(0xc820472160, 0xc82006c700, 0xc82012df20, 0x1fffffffe)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:457 +0x4a3
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet/ip4.(*Main).addDelInterfaceRoutes(0xc82006c700, 0x100000020)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:482 +0x37f
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet/ip4.(*Main).swIfAdminUpDown.func1(0x20, 0xc820649480, 0x0, 0x0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:563 +0x45
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet/ip.(*ifAddressMain).ForeachIfAddress(0xc82006cb58, 0xc80000000d, 0xc838175c30, 0x0, 0x0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip/interface.go:74 +0xc6
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet/ip4.(*Main).swIfAdminUpDown(0xc82006c700, 0xc82018e000, 0xd, 0x0, 0x0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:565 +0x89
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.swIfAdminUpDown)-fm(0xc82018e000, 0xd, 0x0, 0x0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/package.go:28 +0x49
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet.(*swIf).SetAdminUp(0xc82081c0d0, 0xc82018e000, 0x568d00, 0x0, 0x0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/interface.go:225 +0xce
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet.Si.SetAdminUp(0xd, 0xc82018e000, 0x4900, 0x0, 0x0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/interface.go:235 +0x8a
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc820a3ef90)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:286 +0x86d
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc820a3efc0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x135
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc82018e000, 0xc820a3efc0)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x48
Mar  1 18:29:35 invader24 goes.vnetd[29345]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc82018e000, 0x7fd622fd51d8, 0xc82018e548)
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x81
Mar  1 18:29:35 invader24 goes.vnetd[29345]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Mar  1 18:29:35 invader24 goes.vnetd[29345]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x120
Mar  1 18:29:35 invader24 goes.redisd[29311]: killed
Mar  1 18:29:35 invader24 goes.nld[29327]: killed
Mar  1 18:29:35 invader24 goes.qsfpio[29331]: killed
Mar  1 18:29:35 invader24 goes.uptimed[29326]: killed
Mar  1 18:29:35 invader24 goes.uptimed[29326]: done
Mar  1 18:29:35 invader24 goes.qsfp[29334]: killed
Mar  1 18:29:35 invader24 goes.qsfp[29334]: done
Mar  1 18:29:35 invader24 goes.i2cd[29354]: killed
Mar  1 18:29:35 invader24 goes.i2cd[29354]: done
Mar  1 18:29:35 invader24 goes.qsfpio[29331]: done
Mar  1 18:29:35 invader24 goes.nld[29327]: done
Mar  1 18:29:35 invader24 goes.redisd[29311]: done
Mar  1 18:29:37 invader24 goes.vnetd[29345]: done
Mar  1 18:29:37 invader24 goes.goes-daemons[29306]: done

- Adding a print in addDelReplace show deleting the same prefix twice:

Mar  1 18:29:35 invader24 goes.vnetd[29345]: addDelReplace 1.1.1.1/24 4294967294 true
Mar  1 18:29:35 invader24 goes.vnetd[29345]: addDelReplace 1.1.1.1/32 4294967294 true
Mar  1 18:29:35 invader24 goes.vnetd[29345]: addDelReplace 1.1.1.1/24 4294967294 true
Mar  1 18:29:35 invader24 goes.vnetd[29345]: panic in addDelReplace 1.1.1.1/24 4294967294 true

**Comment by stigt** [comment]
- If I comment out the panic, it continues to call addDelReplace with the same prefix:

root@invader24:/home/stig# goes vnet show ip fib | grep eth-1-1
     0                    1.1.1.0/24  579: glean eth-1-1
     0                    1.1.1.1/32  580: local eth-1-1
     0                    1.1.1.2/32  581: rewrite eth-1-1 IP4: 6c:ec:5a:07:d1:a0 -> 00:01:02:03:04:05
     0                    1.1.1.5/32  582: rewrite eth-1-1 IP4: 6c:ec:5a:07:d1:a0 -> 01:02:03:04:05:06

- Note 3 different /32s, but addDelReplace is call with 1.1.1.1/32 instead of 1.1.1.2/32 and 1.1.1.5/32

Mar  1 20:16:13 invader24 goes.vnetd[28288]: addDelReplace 1.1.1.1/24 4294967294 true
Mar  1 20:16:13 invader24 goes.vnetd[28288]: addDelReplace 1.1.1.1/32 4294967294 true
Mar  1 20:16:13 invader24 goes.vnetd[28288]: addDelReplace 1.1.1.1/24 4294967294 true
Mar  1 20:16:13 invader24 goes.vnetd[28288]: addDelReplace 1.1.1.1/32 4294967294 true

- Also note it's called with the null AdjNil.

**Comment by stigt** [comment]
- This is reproducible every time on inv24 without any traffic running:
```
root@invader24:/home/platina# goes restart
root@invader24:/home/platina# ip link set up eth-1-1
root@invader24:/home/platina# ip add add 1.1.1.1/24 dev eth-1-1
root@invader24:/home/platina# goes stop
```

- The 1st delete comes via a netlink message:

May 22 18:53:37 invader24 goes.vnetd[27481]: **addDelReplace 1.1.1.1/24 4294967294 true**
May 22 18:53:37 invader24 goes.vnetd[27481]: addDelReplace 1.1.1.1/32 4294967294 true
May 22 18:53:37 invader24 goes.vnetd[27481]: goroutine 28 [running]:
May 22 18:53:37 invader24 goes.vnetd[27481]: runtime/debug.Stack(0xc42000e018, 0xc42101fc48, 0x4)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
May 22 18:53:37 invader24 goes.vnetd[27481]: runtime/debug.PrintStack()
May 22 18:53:37 invader24 goes.vnetd[27481]:         /usr/local/go/src/runtime/debug/stack.go:16 +0x22
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDelReplace(0xc4201682c0, 0xc4201ec000, 0xc4204d72a0, 0x1fffffffe)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:462 +0x2b4
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Main).addDelInterfaceRoutes(0xc4201ec000, 0x100000020)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:509 +0x1e8
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Main).AddDelInterfaceAddress(0xc4201ec000, 0xc400000004, 0xc4204d7298, 0xc420090501, 0x1, 0x0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:545 +0x363
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/unix.(*Main).ip4IfaddrMsg(0xc4201f4500, 0xc4200a4370, 0x0, 0x0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:451 +0x380
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc420b98810)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:344 +0x42f
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc420b98840)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420196000, 0xc420b98840)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420196000, 0x131e660, 0xc420196548)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
May 22 18:53:37 invader24 goes.vnetd[27481]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124


- The 2nd delete that fails comes from ForeachIfAddress():

May 22 18:53:37 invader24 goes.vnetd[27481]: ForeachIfAddress 32 &{{[1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0] 24} 4 4294967294 4294967295 0}
May 22 18:53:37 invader24 goes.vnetd[27481]: **addDelReplace 1.1.1.1/24 4294967294 true**
May 22 18:53:37 invader24 goes.vnetd[27481]: f.mapFib.unset 1.1.1.1/24
May 22 18:53:37 invader24 goes.vnetd[27481]: ouch: goroutine 28 [running]:
May 22 18:53:37 invader24 goes.vnetd[27481]: runtime/debug.Stack(0xc42101f960, 0xa83380, 0xc4204d75b0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc420196000)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
May 22 18:53:37 invader24 goes.vnetd[27481]: panic(0xa83380, 0xc4204d75b0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDel(0xc4201682c0, 0xc4201ec000, 0xc4204d7540, 0x1fffffffe, 0x0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:186 +0x539
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDelReplace(0xc4201682c0, 0xc4201ec000, 0xc4204d7540, 0x1fffffffe)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:464 +0x1ee
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Main).addDelInterfaceRoutes(0xc4201ec000, 0x100000020)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:492 +0x191
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Main).swIfAdminUpDown.func1(0xc400000020, 0xc4211f6480, 0x3, 0x58)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:573 +0x3d
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip.(*ifAddressMain).ForeachIfAddress(0xc4201ec458, 0xffffffff00000004, 0xc42101fd78, 0x967112, 0xc42101fda0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip/interface.go:75 +0x198
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Main).swIfAdminUpDown(0xc4201ec000, 0xc420196000, 0x4, 0x2, 0x1)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:575 +0x82
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.swIfAdminUpDown)-fm(0xc420196000, 0x4, 0xc420114ae0, 0x0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/package.go:28 +0x45
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet.(*swIf).SetAdminUp(0xc42092e840, 0xc420196000, 0xc42101fe00, 0x62fb36d, 0x47e586479bbec625)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/interface.go:225 +0xa5
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet.Si.SetAdminUp(0x4, 0xc420196000, 0x300, 0xc4200905f8, 0x42c301)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/interface.go:235 +0x63
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc420430030)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:335 +0x829
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc420bd00f0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420196000, 0xc420bd00f0)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
May 22 18:53:37 invader24 goes.vnetd[27481]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420196000, 0x131e660, 0xc420196548)
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
May 22 18:53:37 invader24 goes.vnetd[27481]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
May 22 18:53:37 invader24 goes.vnetd[27481]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124

**Comment by stigt** [comment]
addDelReplace no longer panic and instead just logs it.  Proper fix in namespace branch.
