### ISSUE TITLE
netlink listen sometimes fails on goes start

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#34]
Apr  3 17:58:54 invader1 goes.redisd[9036]: listen: /run/goes/socks/redisd
Apr  3 17:58:54 invader1 goes.redisd[9036]: listen: [127.0.0.1%lo]:6379
Apr  3 17:58:54 invader1 goes.redisd[9036]: listen: [::1%lo]:6379
Apr  3 17:58:54 invader1 goes.redisd[9036]: listen: [192.168.101.206%eth0]:6379
Apr  3 17:58:54 invader1 goes.redisd[9036]: listen: [192.168.101.121%eth0]:6379
Apr  3 17:58:54 invader1 goes.redisd[9036]: listen: [fe80::46:8aff:fe00:2a0%eth0]:6379
Apr  3 17:58:56 invader1 goes.i2cd[9049]: listen OKAY
Apr  3 17:59:01 invader1 goes.i2cd[9049]: Error doing I2C R/W: bus 0x0 addr 0x50 offset 0x7f data 0x3 RW 0 BusSize 2 delay 0
Apr  3 17:59:01 invader1 goes.qsfp[9068]: i2cReq error:write: no such device or address
Apr  3 17:59:01 invader1 goes.i2cd[9049]: Error doing I2C R/W: bus 0x0 addr 0x50 offset 0x7f data 0x0 RW 0 BusSize 2 delay 0
Apr  3 17:59:01 invader1 goes.qsfp[9068]: i2cReq error:write: no such device or address
Apr  3 17:59:01 invader1 goes.qsfp[9068]: QSFP detected in port 1: Unspecified, Molex Inc., 1002971301, 526520698
Apr  3 17:59:01 invader1 goes.i2cd[9049]: Error doing I2C R/W: bus 0x0 addr 0x50 offset 0x7f data 0x0 RW 0 BusSize 2 delay 0
Apr  3 17:59:01 invader1 goes.qsfp[9068]: i2cReq error:write: no such device or address
Apr  3 17:59:01 invader1 goes.vnetd[9061]: panic: invalid argument
Apr  3 17:59:01 invader1 goes.vnetd[9061]: 
Apr  3 17:59:01 invader1 goes.vnetd[9061]: goroutine 467 [running]:
Apr  3 17:59:01 invader1 goes.vnetd[9061]: panic(0xe20320, 0xc820c91270)
Apr  3 17:59:01 invader1 goes.vnetd[9061]:         /usr/local/go/src/runtime/panic.go:464 +0x3e6
Apr  3 17:59:01 invader1 goes.vnetd[9061]: github.com/platinasystems/go/vnet/unix.(*netlinkMain).LoopInit(0xc820110df8, 0xc8200d2b00)
Apr  3 17:59:01 invader1 goes.vnetd[9061]:         /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:176 +0x1e6
Apr  3 17:59:01 invader1 goes.vnetd[9061]: github.com/platinasystems/go/elib/loop.(*Loop).callInitNode.func1.1(0x7ff3a41f8c40, 0xc820110df8, 0xc8200d2b00, 0xc8200d2be0)
Apr  3 17:59:01 invader1 goes.vnetd[9061]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/loop.go:408 +0x31
Apr  3 17:59:01 invader1 goes.vnetd[9061]: created by github.com/platinasystems/go/elib/loop.(*Loop).callInitNode.func1
Apr  3 17:59:01 invader1 goes.vnetd[9061]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/loop.go:410 +0x90
Apr  3 17:59:04 invader1 goes.vnetd[9061]: exit status 2

**Comment by stigt** [comment]
The following patch does a retry which seems the workaround the issue.  Question is, why is the listen failing and is it a valid fix to retry or is the masking some other issue.  Also how many retries should we try (I've seen it sometimes require 4 retries).

diff --git a/internal/netlink/socket.go b/internal/netlink/socket.go
index 5094204..2c605ab 100644
--- a/internal/netlink/socket.go
+++ b/internal/netlink/socket.go
@@ -226,14 +226,20 @@ func (s *Socket) Listen(handler Handler, reqs ...ListenReq) (err error) {
                if r.MsgType == NLMSG_NOOP {
                        continue
                }
-               msg := NewGenMessage()
-               msg.Type = r.MsgType
-               msg.Flags = NLM_F_REQUEST | NLM_F_DUMP
-               msg.AddressFamily = r.AddressFamily
-               s.Tx <- msg
-               err := s.RxUntilDone(handler)
-               if err != nil {
-                       return err
+               for tries := 1; true; tries++ {
+                       msg := NewGenMessage()
+                       msg.Type = r.MsgType
+                       msg.Flags = NLM_F_REQUEST | NLM_F_DUMP
+                       msg.AddressFamily = r.AddressFamily
+                       s.Tx <- msg
+                       err := s.RxUntilDone(handler)
+                       if err == nil {
+                               break
+                       }
+                       if tries >= 10 {
+                               return err
+                       }
+                       fmt.Println("RxUntilDone retry", tries)
                }
        }
        return nil

**Comment by stigt** [comment]
Fixed with -https://github.com/platinasystems/go/commit/0bd1317813e7eab4b164af12474bf7db742e8abe
