### ISSUE TITLE
master branch of fe1 crash on beta hw but not alpha hw

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#35]
In tuntap mode I get a crash on invader24 (beta hw) but not on invader1 (alpha hw).

panic: add-next fe1-rx-vlan-redirect: unknown next meth-0

goroutine 1 [running]:
panic(0xd70840, 0xc8204c6a60)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/platinasystems/go/elib/loop.(*Loop).graphInit(0xc820186000)
        /home/stig/go/src/github.com/platinasystems/go/elib/loop/call.go:280 +0x1cd
github.com/platinasystems/go/elib/loop.(*Loop).Run(0xc820186000)
        /home/stig/go/src/github.com/platinasystems/go/elib/loop/loop.go:444 +0x13a
github.com/platinasystems/go/vnet.(*Vnet).Run(0xc820186000, 0xc8201560e0, 0x0, 0x0)
        /home/stig/go/src/github.com/platinasystems/go/vnet/vnet.go:62 +0xaa
github.com/platinasystems/go/internal/goes/cmd/vnetd.(*cmd).Main(0xc820186000, 0xc82006a160, 0x0, 0x0, 0x0, 0x0)
        /home/stig/go/src/github.com/platinasystems/go/internal/goes/cmd/vnetd/vnetd.go:116 +0x876
github.com/platinasystems/go/internal/goes.(mainer).Main-fm(0xc82006a160, 0x0, 0x0, 0x0, 0x0)
        /home/stig/go/src/github.com/platinasystems/go/internal/goes/goes.go:223 +0x5e
github.com/platinasystems/go/internal/goes.ByName.Main(0xc82013e540, 0xc82006a160, 0x0, 0x0, 0x0, 0x0)
        /home/stig/go/src/github.com/platinasystems/go/internal/goes/goes.go:192 +0xce6
main.main()
        /home/stig/go/src/github.com/platinasystems/go/main/goes-platina-mk1/main.go:14 +0x40

**Comment by stigt** [comment]
The following patch appears to work around the issue, but not sure it's the "right" fix.  Tom mentioned getting the names from netlink rather than generating them.

`diff --git a/internal/fe1a/port_init.go b/internal/fe1a/port_init.go
index b014551..3ea3a76 100644
--- a/internal/fe1a/port_init.go
+++ b/internal/fe1a/port_init.go
@@ -222,7 +222,7 @@ func (t *fe1a) addPort(p *Port, pb *port.PortBlock) {
        }
        if !p.IsManagement {
                pp.Vlan = uint16(vlan_for_port(p.physical_port_number))
-               pp.RedirectTo = fmt.Sprintf("meth-%d", punt_management_ethernet_for_port(p.physical_port_number))
+               pp.RedirectTo = fmt.Sprintf("meth-%d", punt_management_ethernet_for_port(p.physical_port_number)+po)
        }
        t.packet_dma_ports[p.physical_port_number.toPipe()] = pp
 }
`

**Comment by stigt** [comment]
Fixed with: https://github.com/platinasystems/fe1/commit/87d0ed69f629bf509830e2a0be053a603dd36bab
