### ISSUE TITLE
panic: unknown link info attribute kind SLAVE_KIND

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#37]
SW Version:  a2dff179aaec9160aa7b0194fa450a9e77261f96

Saw this trying to install goes on Invader2.  Reproducible 100% of the time.
platina@invader2:$ sudo ./goes-latest install
start: (platina,vnet.ready) timeout
install: start: exit status 1

syslog shows:
Apr 16 21:32:37 invader2 goes.vnetd[28108]: panic: unknown link info attribute kind SLAVE_KIND
Apr 16 21:32:37 invader2 goes.vnetd[28108]:
Apr 16 21:32:37 invader2 goes.vnetd[28108]: goroutine 25 [running]:
Apr 16 21:32:37 invader2 goes.vnetd[28108]: panic(0xa4aa00, 0xc4207ecec0)
Apr 16 21:32:37 invader2 goes.vnetd[28108]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 16 21:32:37 invader2 goes.vnetd[28108]: github.com/platinasystems/go/internal/netlink.parse_link_info(0xc4202177bc, 0xe8, 0xc844, 0xc420bf6fc0)
Apr 16 21:32:37 invader2 goes.vnetd[28108]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/netlink/attr.go:217 +0x3b4
Apr 16 21:32:37 invader2 goes.vnetd[28108]: github.com/platinasystems/go/internal/netlink.(*IfInfoMessage).Write(0xc420be5500, 0xc4202175a0, 0x5d8, 0xca60, 0x4e0, 0x0, 0x0)
Apr 16 21:32:37 invader2 goes.vnetd[28108]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/netlink/msg.go:430 +0x4e8
Apr 16 21:32:37 invader2 goes.vnetd[28108]: github.com/platinasystems/go/internal/netlink.(*Socket).gorx(0xc4201ff400)
Apr 16 21:32:37 invader2 goes.vnetd[28108]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/netlink/socket.go:338 +0x34a
Apr 16 21:32:37 invader2 goes.vnetd[28108]: created by github.com/platinasystems/go/internal/netlink.NewWithConfig
Apr 16 21:32:37 invader2 goes.vnetd[28108]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/netlink/socket.go:199 +0x646
Apr 16 21:32:39 invader2 goes.vnetd[28108]: exit status 2

Same version of SW installed OK on invader7, so looks that there may be some dependencies.

**Comment by fszyang** [comment]
Looks like the reason goes panic on invader2 is that invader2 has docker image with a veth port up (use for something else not related to goes). 

I added an additional print to the panic statement in parse_link_info() and it is failing when trying to parse a veth kind

panic: unknown link info attribute kind SLAVE_KIND AttrArray.String:KIND: veth

Need to handle veth link messages

**Comment by fszyang** [comment]
Fixed by   Commit: 37f042a904cd6274d9e7144408281b450fd7011e
Verified
