### ISSUE TITLE
mmu port flush timeout

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#45]
This issue looks to be there still with latest commits from 4/27
Version: 74dfc8b
(also included commit c7d5054515784cb33860ef15aa5e5f4d17fdd4ea in fe1)

Setup
(                 pkgen                      )
 |       |      |      |      |      |      |      |
e01 e03 e05 e07 e09 e11 e13 e15     (  invader 7 )
e00 e02 e04 e06 e08 e10 e12 e14 e16 e18 e20 e22 e24 e26 e28 e30
 |       |      |      |      |      |      |      |      |       |      |      |      |      |      |      |
e00 e02 e04 e06 e08 e10 e12 e14 e16 e18 e20 e22 e24 e26 e28 e30
           ( invader 2 )                         e17 e19 e21 e23 e25 e27 e29 e31
                                                         |       |      |      |      |      |      |      |
                                                        (                 pkgen                      )

bidirectional traffic going from between the pkgen through invader2 and invader7

Step to reproduce:
Restart goes on invader2 (all ports on invader2 will flap)
Gets panic on invader7

Apr 28 13:01:57 invader7 goes.vnetd[1585]: mmu port flush timeout: eth-14-0: goroutine 199 [running]:
Apr 28 13:01:57 invader7 goes.vnetd[1585]: runtime/debug.Stack(0xc420035c50, 0xa54b20, 0xc42023a350)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Apr 28 13:01:57 invader7 goes.vnetd[1585]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc420194000)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x91
Apr 28 13:01:57 invader7 goes.vnetd[1585]: panic(0xa54b20, 0xc42023a350)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /usr/local/go/src/runtime/panic.go:458 +0x243
Apr 28 13:01:57 invader7 goes.vnetd[1585]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*Port).mmu_port_flush(0xc4203b9c70, 0xc42026e000)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/mmu.go:390 +0x246
Apr 28 13:01:57 invader7 goes.vnetd[1585]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).LinkStatusChange(0xc42026e000, 0xc420b06d28)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/port_init.go:591 +0x510
Apr 28 13:01:57 invader7 goes.vnetd[1585]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/cpu.(*linkStatusEvent).EventAction(0xc420b06d20)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/cpu/link_scan.go:239 +0x48
Apr 28 13:01:57 invader7 goes.vnetd[1585]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc420bd3320)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
Apr 28 13:01:57 invader7 goes.vnetd[1585]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420194000, 0xc420bd3320)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
Apr 28 13:01:57 invader7 goes.vnetd[1585]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420194000, 0x12d7380, 0x12f6500)
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
Apr 28 13:01:57 invader7 goes.vnetd[1585]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Apr 28 13:01:57 invader7 goes.vnetd[1585]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
Apr 28 13:01:57 invader7 goes.vnetd[1585]: done

**Comment by fszyang** [comment]
Closed
Fixed in fe1 version 4817d1d90a9e5610cd44a71d23f68c1b5726d3d0
Verified in goes version 98f3841b3f6310a316a166d78c519dba9d3e31dd
                               fe1: f823d6e1f564397570e68f4f1e2d43c02ccdc79c

Tested both fixed-100g and autoneg ports.  No more panics.
