### ISSUE TITLE
Fib multipath for shared adjacency

### ISSUE THREAD

**Issue by dlobete** [platinasystems/go#50]
In a namespace environment a learned route seems to be treated as a multipath:

root@invader5:/home/dlobete# goes vnet show ip fib
 Table                   Destination           Adjacency
     0                   31.0.0.0/24       5: glean eth-24-0
     0                   31.0.0.5/32       6: local eth-24-0
     2                   10.0.0.0/24       3: glean eth-1-0
     2                   10.0.0.1/32       4: local eth-1-0
                                        tx pipe packets                2
                                        tx pipe bytes                148
     2                   10.0.0.2/32      12: rewrite eth-1-0 IP4: 02:46:8a:00:04:36 -> 02:46:8a:00:04:37
     2                   30.0.0.0/24       9: glean eth-10-0
     2                   30.0.0.5/32      10: local eth-10-0
     3                   10.0.0.0/24       7: glean eth-2-0
     3                   10.0.0.1/32      11: rewrite eth-2-0 IP4: 02:46:8a:00:04:37 -> 02:46:8a:00:04:36
     3                   10.0.0.2/32       8: local eth-2-0
                                        tx pipe packets                2
                                        tx pipe bytes                148
     3                   30.0.0.0/24      13: rewrite eth-2-0 IP4: 02:46:8a:00:04:37 -> 02:46:8a:00:04:36 13-13, 1 x 11

Probably the last entry in table 3 for 30.0.0.0/24 should share the adjacency (11) instead of having its own adjacency (13).

Very intermittently on a teardown of the namespace I see a panic in vnet:

May 23 15:58:08 invader5 goes.vnetd[544]: runtime error: invalid memory address or nil pointer dereference: goroutine 39 [running]:
May 23 15:58:08 invader5 goes.vnetd[544]: runtime/debug.Stack(0xc42093b860, 0xadb800, 0x1201470)
May 23 15:58:08 invader5 goes.vnetd[544]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc420196000)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
May 23 15:58:08 invader5 goes.vnetd[544]: panic(0xadb800, 0x1201470)
May 23 15:58:08 invader5 goes.vnetd[544]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/vnet/ip4.(*Fib).mapFibRemapAdjacency(0x0, 0xc420184380, 0xfffffffe0000000f)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/vnet/ip4/fib.go:252 +0x48
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/vnet/ip4.(*Main).remapAdjacency(0xc420184380, 0xfffffffe0000000f)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/vnet/ip4/fib.go:273 +0x78
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.remapAdjacency)-fm(0xfffffffe0000000f)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/vnet/ip4/package.go:25 +0x3a
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/vnet/ip.(*Main).delMultipathAdj(0xc4201843e8, 0x10000000e)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/vnet/ip/adjacency.go:615 +0x1fc
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/vnet/ip.(*Main).FreeAdj(0xc4201843e8, 0x10000000e)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/vnet/ip/adjacency.go:553 +0x65
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/vnet/ip.(*Main).DelAdj(0xc4201843e8, 0xe0000000e)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/vnet/ip/adjacency.go:560 +0x4e
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/vnet/ethernet.(*ipNeighborMain).AddDelIpNeighbor(0xc420162668, 0xc4201843e8, 0xc4213481a0, 0x2c04000001, 0x1, 0x0)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/vnet/ethernet/neighbor.go:90 +0x5a9
May 23 15:58:08 invader5 goes.vnetd[544]: github.com/platinasystems/go/vnet/unix.(*Main).ip4NeighborMsg(0xc4201e2500, 0xc4200ec540, 0x0, 0x0)
May 23 15:58:08 invader5 goes.vnetd[544]:         /home/dlobete/src/github.com/platinasystems/go/vnet/unix/netlink.go:488 +0x322

**Comment by dlobete** [comment]
The crash described above is addressed by Stig's fix to remapAdjacency().
