### ISSUE TITLE
Crash after 'vnet sho ip fib'

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#52]
After stopping 3 docker containers:
```
donn@invader17:~/workspace/docker/gobgp$ dc down
Stopping gobgp_gobgp10_1 ... done
Stopping gobgp_gobgp1_1 ... done
Stopping gobgp_gobgp2_1 ... done
Removing gobgp_gobgp10_1 ... done
Removing gobgp_gobgp1_1 ... done
Removing gobgp_gobgp2_1 ... done
Removing network gobgp_default
donn@invader17:~/workspace/docker/gobgp$
```

I brought up the 3 containers:

```
donn@invader17:~/workspace/docker/gobgp$ dc up -d
Creating network "gobgp_default" with the default driver
Creating gobgp_gobgp10_1
Creating gobgp_gobgp1_1
Creating gobgp_gobgp2_1
donn@invader17:~/workspace/docker/gobgp$
```

I did 'sho fib' and vnet crashed.

```
donn@invader17:~/workspace/docker/gobgp$ sudo goes vnet sho ip fib | less
```

```
donn@invader17:~/workspace/docker/gobgp$ ps -e f
...
18319 ?        Ssl    0:02 goes-daemons
18325 ?        Sl     0:06  \_ redisd
18339 ?        Sl     1:58  \_ i2cd
18345 ?        Sl     0:21  \_ qsfp
18349 ?        Sl     0:00  \_ uptimed
22643 ?        Ss     0:00 ssh-agent
donn@invader17:~/workspace/docker/gobgp$ 
```

```
May 25 16:06:33 invader17 goes.vnetd[18341]: addDelReplace: goroutine 52 [running]:
May 25 16:06:33 invader17 goes.vnetd[18341]: runtime/debug.Stack(0xc421219b40, 0xa82e60, 0xc42073d360)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc4201a0000)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
May 25 16:06:33 invader17 goes.vnetd[18341]: panic(0xa82e60, 0xc42073d360)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDelReplace(0xc420172580, 0xc420190380, 0xc42073d350,
0x1fffffffe)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:455 +0xd1
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet/ip4.(*Main).addDelInterfaceRoutes(0xc420190380, 0x10000000e)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:480 +0x191
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet/ip4.(*Main).swIfAdminUpDown.func1(0xe, 0xc4200e81f8, 0x8ef2e7, 0xc4
20190380)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:561 +0x3d
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet/ip.(*ifAddressMain).ForeachIfAddress(0xc4201907d8, 0xffffffff000000
04, 0xc421219d58, 0x966be2, 0xc421219d80)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip/interface.go:74 +0x78
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet/ip4.(*Main).swIfAdminUpDown(0xc420190380, 0xc4201a0000, 0x4, 0x2, 0
x1)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:563 +0x82
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.swIfAdminUpDown)
-fm(0xc4201a0000, 0x4, 0xc4201b1820, 0x0)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/package.go:28 +0x45
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet.(*swIf).SetAdminUp(0xc42072b440, 0xc4201a0000, 0xc421219e00, 0x4cff038e, 0x85a2a35e74a071a6)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/interface.go:225 +0xa5
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet.Si.SetAdminUp(0x4, 0xc4201a0000, 0x0, 0xc420090668, 0xc400000001)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/interface.go:235 +0x63
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc4205d1740)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:334 +0x8c2
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc420d171d0)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc4201a0000, 0xc420d171d0)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
May 25 16:06:33 invader17 goes.vnetd[18341]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc4201a0000, 0x131f960, 0xc4201a0548)
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
May 25 16:06:33 invader17 goes.vnetd[18341]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
May 25 16:06:33 invader17 goes.vnetd[18341]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
May 25 16:06:33 invader17 goes.vnetd[18341]: done
May 25 16:06:36 invader17 kernel: DMAR: DRHD: handling fault status reg 2
May 25 16:06:36 invader17 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr fff7a000 [fault reason 05] PTE Write access is not set
May 25 16:06:36 invader17 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr fff7a000 [fault reason 05] PTE Write access is not set
May 25 16:06:36 invader17 kernel: DMAR: DRHD: handling fault status reg 200
```

**Comment by dlobete** [comment]
Donn,
Could you confirm vnet didn't crash after the tear down?
Thanks,
Don.

**Comment by donnlee** [comment]
I'm didn't confirm on 5/25 whether vnet crashed after containers were downed, but it just happened again on i16 and this time no containers were disturbed (or stopped):

```
May 31 12:28:38 invader16 kernel: ixgbe 0000:03:00.0 eth1: VF Reset msg received from vf 0
May 31 12:28:38 invader16 goes.vnetd[15505]: addDelReplace: goroutine 66 [running]:
May 31 12:28:38 invader16 goes.vnetd[15505]: runtime/debug.Stack(0xc4208c5b40, 0xa82e40, 0xc4207e80b0)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc420162000)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
May 31 12:28:38 invader16 goes.vnetd[15505]: panic(0xa82e40, 0xc4207e80b0)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDelReplace(0xc420088580, 0xc420177b00, 0xc4207e80a8, 0x1fffffffe)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/ip4/fib.go:455 +0xd1
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet/ip4.(*Main).addDelInterfaceRoutes(0xc420177b00, 0x100000020)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/ip4/fib.go:480 +0x191
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet/ip4.(*Main).swIfAdminUpDown.func1(0x20, 0xc420ff4b80, 0x8ef2d7, 0xc420177b00)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/ip4/fib.go:561 +0x3d
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet/ip.(*ifAddressMain).ForeachIfAddress(0xc420177f58, 0xffffffff00000004, 0xc4208c5d58, 0x966bd2, 0xc4208c5d80)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/ip/interface.go:74 +0x78
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet/ip4.(*Main).swIfAdminUpDown(0xc420177b00, 0xc420162000, 0x4, 0x2, 0x1)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/ip4/fib.go:563 +0x82
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.swIfAdminUpDown)-fm(0xc420162000, 0x4, 0xc4201b2b60, 0x0)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/ip4/package.go:28 +0x45
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet.(*swIf).SetAdminUp(0xc42019b840, 0xc420162000, 0xc4208c5e00, 0xfd69eb9, 0x40db28a383c36cfa)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/interface.go:225 +0xa5
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet.Si.SetAdminUp(0x4, 0xc420162000, 0x100, 0xc4200904a8, 0xc400000001)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/interface.go:235 +0x63
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc420896510)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:334 +0x8c2
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc420896330)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420162000, 0xc420896330)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
May 31 12:28:38 invader16 goes.vnetd[15505]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420162000, 0x131e960, 0xc420162548)
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
May 31 12:28:38 invader16 goes.vnetd[15505]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
May 31 12:28:38 invader16 goes.vnetd[15505]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
May 31 12:28:38 invader16 goes.vnetd[15505]: netlink RTM_DELROUTE:
May 31 12:28:38 invader16 goes.vnetd[15505]: nsid: 4294967295
May 31 12:28:38 invader16 goes.vnetd[15505]: len: 116
May 31 12:28:38 invader16 goes.vnetd[15505]: seq: 0
May 31 12:28:38 invader16 goes.vnetd[15505]: pid: 0
...
```

My commands before I noticed the crash:

```
 1634  echo $CONTAINER_PID
 1635  sudo ip netns exec $CONTAINER_PID ip add add 192.168.217.116/24 dev eth-1-1
```

Then i noticed i16 lost IP reachability.  Then I tried:

```
 1637  sudo goes vnet show fe1 po ma
```

which failed

```
donn@invader16:~/workspace/docker/gobgp$ sudo goes vnet show fe1 po ma
vnet: /run/goes/socks/vnet: timeout
```

Containers were not disturbed:

```
donn@invader16:~/workspace/docker/gobgp$ d ps
CONTAINER ID        IMAGE                  COMMAND               CREATED             STATUS              PORTS               NAMES
18b6c2c8a25e        donn/gobgp-jessie      "tail -f /dev/null"   4 days ago          Up 4 days                               gobgp_gobgp_1
2aba64de60ec        donn/collectd-docker   "/root/run.sh"        4 weeks ago         Up 6 days                               collectddocker_collectd_1
```

**Comment by donnlee** [comment]
I suspect this cmd caused the vnet panic:

`sudo ip netns exec $CONTAINER_PID ip add add 192.168.217.116/24 dev eth-1-1`

**Comment by stigt** [comment]
I have also run into this several times running docker and crashing in addDelReplace.  Eliot says it's fixed in the namespace branch, but for now in master it will just log instead of panic when I tries to delete the same prefix multiple times.  Patch in master -https://github.com/platinasystems/go/commit/dcb42afc1f93cfd8a6d1d4cdb8c6549f37d3761f
