### ISSUE TITLE
Moving an sriov interface into a docker sometimes hangs vnet

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#54]
- I have the following interface on inv1:

```
stig@invader1:~/docker/docker-quagga$ ip add sh eth-0-0
1084: eth-0-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:46:8a:00:02:a3 brd ff:ff:ff:ff:ff:ff
    inet 10.15.0.1/24 scope global eth-0-0
       valid_lft forever preferred_lft forever
    inet 10.16.0.1/24 scope global eth-0-0
       valid_lft forever preferred_lft forever
    inet6 fe80::46:8aff:fe00:2a3/64 scope link 
       valid_lft forever preferred_lft forever
```
- Using Donn Lee's script I move eth-0-0 to docker container R1:

```
stig@invader1:~/docker/docker-quagga$ sudo ./move-intf.sh eth-0-0 R1 10.15.0.1/24
directory check: ok
symlink for pid 24247 exists.
nsid 2 (iproute2 netns name: 24247)
nsid check: ok
1084: eth-0-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 02:46:8a:00:02:a3 brd ff:ff:ff:ff:ff:ff

```

- I can see the interface in container R1:
 
```
stig@invader1:~/docker/docker-quagga$ docker exec -it R1 ip add sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
1084: eth-0-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:46:8a:00:02:a3 brd ff:ff:ff:ff:ff:ff
    inet 10.15.0.1/24 scope global eth-0-0
       valid_lft forever preferred_lft forever
    inet6 fe80::46:8aff:fe00:2a3/64 scope link 
       valid_lft forever preferred_lft forever
408: eth0@if409: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link 
       valid_lft forever preferred_lft forever
```

- Vnet is still running but hangs on vnet commands.  It does not happen on all interfaces and it seems like if I don't have an ip address on the interface, then it moves to the container without hanging vnet.

**Comment by stigt** [comment]
Donn's script:
```
#!/bin/bash

set -e

if ! [ $(id -u) = 0 ]; then
   echo "You must run this script as root/sudo."
   exit 1
fi

if [ $# -lt 3 ]; then
    echo "Usage: $0 <interface_to_move> <container_name> <ip_with_mask>"
    echo "eg. $0 eth-30-1 gobgp_gobgp1_1 192.168.200.1/24"
    exit 1
fi

IFC_NAME=$1
CONTAINER_NAME=$2
ADDRESS_WITH_MASK=$3

if [ -d "/var/run/netns" ]; then
  echo "directory check: ok"
else
  echo "Expected netns directory, but it doesn't exist!"
  echo "Creating directory"
  mkdir -p /var/run/netns
fi

CONTAINER_PID=$(docker inspect -f '{{.State.Pid}}' $CONTAINER_NAME) || echo "Failed to find container named $CONTAINER_NAME."
if [ -z $CONTAINER_PID ]; then
  exit 2
fi

if [ -h /var/run/netns/$CONTAINER_PID ]; then
  echo "symlink for pid $CONTAINER_PID exists."
else
  echo "creating symlink for pid $CONTAINER_PID"
  ln -s /proc/$CONTAINER_PID/ns/net /var/run/netns/$CONTAINER_PID
fi

ip netns list-id | grep "name: $CONTAINER_PID"

if [ $? -eq 0 ]; then
  echo "nsid check: ok"
else
  echo "Something went wrong. Expected namespace name $CONTAINER_PID in output of 'ip netns list-id'"
  exit 3
fi

ip link sho $IFC_NAME
if [ $? -ne 0 ]; then
  echo "Interface $IFC_NAME doesn't exist in the default namespace."
  exit 4
fi

ip link set $IFC_NAME netns $CONTAINER_PID
if [ $? -ne 0 ]; then
  echo "'set $IFC_NAME' failed."
  exit 5
fi

ip netns exec $CONTAINER_PID ip addr add $ADDRESS_WITH_MASK dev $IFC_NAME
if [ $? -ne 0 ]; then
  echo "Failed to set ip address."
  exit 6
fi

ip netns exec $CONTAINER_PID ip link set $IFC_NAME up
if [ $? -ne 0 ]; then
  echo "Failed to bring-up interface in container."
  exit 7
fi
```

**Comment by stigt** [comment]
This bug appears to be related to a secondary address on an interface when it is moved.  It can be worked around either by:

1) restart goes without the secondary, then use the move script.  If goes ever saw the secondary, then even if it is removed the move will still hang vnet.

2) oddly enough if the move script is modified to 1st bring up the interface, then add the address.  Then the move will not hang vnet.  So it could be a timing issue with vnet getting both a IfInfoMessage and IfAddrMessage at the same time.

**Comment by stigt** [comment]
Wrote a script to move interfaces in and out of a docker.  It ran over 500 iterations of moving in & out of a docker container without crashing or hanging vnet.  I was going to mark it closed at that point, but then I noticed it crashed at iteration 505.  Re-ran multiple times and each time it crashed at iteration 505 with the following stack trace:
```
runtime error: index out of range: goroutine 68 [running]:
runtime/debug.Stack(0xc421edf7f8, 0xb18000, 0x1329150)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
/go/elib/loop.(*Loop).doEvent.func1(0xc420170000)
        /home/stig/go/src//go/elib/loop/event.go:128 +0x72
panic(0xb18000, 0x1329150)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
/fe1/internal/fe1a.(*garbage_dump_rxf_pipe).add_del_rule(0xc420207ed8, 0xc420206a80, 0xc420204080, 0x5, 0xc421edfcf8, 0x0)
        /home/stig/go/src//fe1/internal/fe1a/dump.go:634 +0x9c5
/fe1/internal/fe1a.(*garbage_dump_rxf_main).rxf_vlan_redirect_add_del(0xc420206a80, 0xc420204080, 0xc421ee1bcc, 0x0)
        /home/stig/go/src//fe1/internal/fe1a/dump.go:679 +0x350
/fe1/internal/fe1a.(*Port).rxf_vlan_redirect_up_down(0xc420693f20, 0xc420204080, 0x10600)
        /home/stig/go/src//fe1/internal/fe1a/l3_interface.go:354 +0x75
/fe1/internal/fe1a.(*Port).port_table_admin_up_down(0xc420693f20, 0xc4201ee000, 0xc420170801)
        /home/stig/go/src//fe1/internal/fe1a/l3_interface.go:393 +0xb9
/fe1/internal/fe1a.(*fe1a).swIfAdminUpDown(0xc4201ee000, 0xc420170000, 0x100000004, 0x0, 0x3)
        /home/stig/go/src//fe1/internal/fe1a/l3_interface.go:423 +0x116
/fe1/internal/fe1a.(*fe1a).(/fe1/internal/fe1a.swIfAdminUpDown)-fm(0xc420170000, 0x100000004, 0xc4201d0040, 0x8e0057)
        /home/stig/go/src//fe1/internal/fe1a/l3.go:27 +0x45
/go/vnet.(*swIf).SetAdminUp(0xc420173c40, 0xc420170000, 0xc4201d6001, 0x100000004, 0x0)
        /home/stig/go/src//go/vnet/interface.go:254 +0xa5
/go/vnet.Si.SetAdminUp(0xc400000004, 0xc420170000, 0xc400000001, 0x0, 0x42c401)
        /home/stig/go/src//go/vnet/interface.go:264 +0x63
/go/vnet/unix.(*netlinkEvent).EventAction(0xc420fc23c0)
        /home/stig/go/src//go/vnet/unix/netlink.go:381 +0x91a
/go/elib/loop.(*loopEvent).do(0xc420fc2420)
        /home/stig/go/src//go/elib/loop/event.go:118 +0x34
/go/elib/loop.(*Loop).doEvent(0xc420170000, 0xc420fc2420)
        /home/stig/go/src//go/elib/loop/event.go:133 +0x51
/go/elib/loop.(*Loop).eventHandler(0xc420170000, 0x144a8a0, 0xc420170568)
        /home/stig/go/src//go/elib/loop/event.go:140 +0x86
created by /go/elib/loop.(*Loop).startHandler
        /home/stig/go/src//go/elib/loop/event.go:153 +0x124
done
```

Script used:
```
cat abuse
#!/bin/bash

set -e

loop=1
while true; do
   echo "loop = $loop"
   ((loop++))
   goes vnet show ip fib
   ./docker_move.sh up R1 eth-0-0 10.15.0.1/24
   goes vnet show ip fib
   ./docker_move.sh down R1 eth-0-0
   goes vnet show ip fib
   goes status
done
```

**Comment by stigt** [comment]
The line of code that crashes is:

    q.t.rx_pipe_mems.rxf_80bit_tcam[0][ri].seta(q, &te[1], sbus.Unique(p.pipe))

The "ri" index max is 512, so it looks like the isn't reusing tcam entries and walked off the end.

**Comment by stigt** [comment]
The initial problem no longer occurs.  The out of resource issue found yesterday was solved with the following commit -https://github.com/platinasystems/fe1/commit/4b9f4f888fb1413cd37930254b9a6c08f2f8af36
