### ISSUE TITLE
"invalid memory address or nil pointer dereference" after '... show fe1 po phy'

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#63]
Brought up a new link with 'ifup eth-7-0'.
Issued 'goes vnet show fe1 po phy' to view the link status. It hung and vnet died.

```
root@invader2:/etc/gobgp# ifup eth-7-0
root@invader2:/etc/gobgp#
root@invader2:/etc/gobgp#
root@invader2:/etc/gobgp#
root@invader2:/etc/gobgp# goes vnet show fe1 po p eth-15-0
^C
root@invader2:/etc/gobgp# goes vnet show fe1 po phy
vnet: /run/goes/socks/vnet: timeout
```

Saw this in syslog:

```
Jul 18 17:28:38 invader2 goes.qsfp[7735]: QSFP detected in port 7: 100GBASE-CR4, Molex Inc., 1002971301, 526520656
Jul 18 17:32:26 invader2 kernel: ixgbevf 0000:03:11.6: NIC Link is Up 10 Gbps
Jul 18 17:32:26 invader2 kernel: IPv6: ADDRCONF(NETDEV_UP): eth-7-0: link is not ready
Jul 18 17:32:26 invader2 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth-7-0: link becomes ready
Jul 18 17:32:26 invader2 goes.vnetd[7743]: runtime error: invalid memory address or nil pointer dereference: goroutine 31 [running]:
Jul 18 17:32:26 invader2 goes.vnetd[7743]: runtime/debug.Stack(0xc42742ba48, 0xb1bca0, 0x132bfd0)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Jul 18 17:32:26 invader2 goes.vnetd[7743]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc4201a2000)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
Jul 18 17:32:26 invader2 goes.vnetd[7743]: panic(0xb1bca0, 0x132bfd0)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
Jul 18 17:32:26 invader2 goes.vnetd[7743]: github.com/platinasystems/go/vnet/ip.(*Main).AddDelNextHop(0xc4201e3068, 0x10000000e, 0x100000055, 0xc42013a858)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip/adjacency.go:478 +0x4c5
Jul 18 17:32:26 invader2 goes.vnetd[7743]: github.com/platinasystems/go/vnet/ip4.(*Main).AddDelRouteNextHop(0xc4201e3000, 0xc4241f1310, 0xc4241f1320, 0x701080
1, 0x1, 0x858b33c87025cf3b)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip4/fib.go:472 +0x1cb
Jul 18 17:32:26 invader2 goes.vnetd[7743]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).ip4RouteMsg(0xc427555620, 0xc4207229c0, 0xc420722901, 0xc423
31fe01, 0x42c444)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:603 +0x1ec
Jul 18 17:32:26 invader2 goes.vnetd[7743]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc427555620)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:399 +0x5a5
Jul 18 17:32:26 invader2 goes.vnetd[7743]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc427555650)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
Jul 18 17:32:26 invader2 goes.vnetd[7743]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc4201a2000, 0xc427555650)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
Jul 18 17:32:26 invader2 goes.vnetd[7743]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc4201a2000, 0x144d760, 0xc4201a2568)
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
Jul 18 17:32:26 invader2 goes.vnetd[7743]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Jul 18 17:32:26 invader2 goes.vnetd[7743]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
Jul 18 17:32:26 invader2 goes.vnetd[7743]: done
Jul 18 17:32:26 invader2 systemd[1]: Reloading OpenBSD Secure Shell server.
Jul 18 17:32:26 invader2 systemd[1]: Failed to reset devices.list on /system.slice: Invalid argument
Jul 18 17:32:26 invader2 systemd[1]: Reloaded OpenBSD Secure Shell server.

**Comment by donnlee** [comment]
```
    version: 1d32f2ce33dd64f0500c5269f6f82917b51d701a
```
(July 13th)

**Comment by donnlee** [comment]
Happened again. so might be reproducible:

```
root@invader2:/etc/gobgp# ifdown eth-7-0
root@invader2:/etc/gobgp# ifup eth-7-0
root@invader2:/etc/gobgp# goes vnet show fe1 po phy | grep "eth-7"
vnet: /run/goes/socks/vnet: timeout

**Comment by donnlee** [comment]
This time I issued the cmds on the neighbor router, i7.  Got a slightly different crash:

```
donn@invader7:~/workspace/gitlab.com/donnlee/tor$ sudo !!
sudo ifup eth-25-0
donn@invader7:~/workspace/gitlab.com/donnlee/tor$
donn@invader7:~/workspace/gitlab.com/donnlee/tor$
donn@invader7:~/workspace/gitlab.com/donnlee/tor$ sudo goes vnet show fe1 po phy | grep "eth-25-0"
vnet: /run/goes/socks/vnet: timeout
```
syslog:
```
Jul 18 17:48:42 invader7 kernel: IPv6: ADDRCONF(NETDEV_UP): eth-25-0: link is not ready
Jul 18 17:48:42 invader7 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth-25-0: link becomes ready
Jul 18 17:48:42 invader7 goes.vnetd[15172]: runtime error: slice bounds out of range: goroutine 26 [running]:
Jul 18 17:48:42 invader7 goes.vnetd[15172]: runtime/debug.Stack(0xc422dfda58, 0xb1bca0, 0x132c020)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc420196000)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
Jul 18 17:48:42 invader7 goes.vnetd[15172]: panic(0xb1bca0, 0x132c020)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/vnet/ip.(*multipathMain).delNextHop(0xc4201de188, 0x0, 0x0, 0x0, 0xc4213401c0, 0x1, 0
x8, 0x0, 0x0, 0x0, ...)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip/adjacency.go:586 +0x170
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/vnet/ip.(*Main).AddDelNextHop(0xc4201de068, 0x10000012b, 0x100000111, 0xc4201323f4)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip/adjacency.go:499 +0x43c
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/vnet/ip4.(*Main).AddDelRouteNextHop(0xc4201de000, 0xc4213f39d0, 0xc4213f39f0, 0x68020
20801, 0x1, 0x50ee7da2757f1082)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip4/fib.go:472 +0x1cb
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).ip4RouteMsg(0xc423c76900, 0xc4231b2340, 0xc4231b2301, 0xc42
30c8901, 0x42c444)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:603 +0x1ec
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc423c76900)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:399 +0x5a5
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc423c76630)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420196000, 0xc423c76630)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
Jul 18 17:48:42 invader7 goes.vnetd[15172]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420196000, 0x144d760, 0xc420196568)
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
Jul 18 17:48:42 invader7 goes.vnetd[15172]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Jul 18 17:48:42 invader7 goes.vnetd[15172]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
Jul 18 17:48:42 invader7 goes.vnetd[15172]: done
Jul 18 17:48:42 invader7 kernel: DMAR: DRHD: handling fault status reg 2
Jul 18 17:48:42 invader7 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr ffc0d000 [fault reason 05] PTE Write access is not set
Jul 18 17:48:42 invader7 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr ffc0e000 [fault reason 05] PTE Write access is not set
Jul 18 17:48:42 invader7 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr ffc03000 [fault reason 05] PTE Write access is not set
Jul 18 17:48:42 invader7 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr ffc04000 [fault reason 05] PTE Write access is not set
Jul 18 17:48:42 invader7 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr ffc05000 [fault reason 05] PTE Write access is not set
Jul 18 17:48:42 invader7 kernel: DMAR: DRHD: handling fault status reg 500
Jul 18 17:48:42 invader7 systemd[1]: Reloading OpenBSD Secure Shell server.
Jul 18 17:48:42 invader7 systemd[1]: Reloaded OpenBSD Secure Shell server.
Jul 18 17:48:42 invader7 kernel: DMAR: DRHD: handling fault status reg 502
```

Same version:
    version: 1d32f2ce33dd64f0500c5269f6f82917b51d701a

Link is set to copper/100g.

**Comment by donnlee** [comment]
crash after `sudo goes start`

```
Jul 25 14:21:22 invader2 kernel: IPv6: ADDRCONF(NETDEV_UP): eth-27-0: link is not ready
Jul 25 14:21:22 invader2 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth-27-0: link becomes ready
Jul 25 14:21:22 invader2 systemd[1]: Reloading OpenBSD Secure Shell server.
Jul 25 14:21:22 invader2 gobgpd[17784]: {"Key":"10.8.2.7","State":"BGP_FSM_OPENCONFIRM","Topic":"Peer","level":"info","msg":"Pe
er Up","time":"2017-07-25T14:21:22-07:00"}
Jul 25 14:21:22 invader2 systemd[1]: Reloaded OpenBSD Secure Shell server.
Jul 25 14:21:22 invader2 kernel: ixgbevf 0000:03:13.1: NIC Link is Up 10 Gbps
Jul 25 14:21:22 invader2 kernel: IPv6: ADDRCONF(NETDEV_UP): eth-28-0: link is not ready
Jul 25 14:21:22 invader2 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth-28-0: link becomes ready
Jul 25 14:21:22 invader2 goes.vnetd[17482]: runtime error: invalid memory address or nil pointer dereference: goroutine 43 [run
ning]:
Jul 25 14:21:22 invader2 goes.vnetd[17482]: runtime/debug.Stack(0xc421471a48, 0xb1bca0, 0x132bfd0)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Jul 25 14:21:22 invader2 goes.vnetd[17482]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc4201a0000)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:128
+0x72
Jul 25 14:21:22 invader2 goes.vnetd[17482]: panic(0xb1bca0, 0x132bfd0)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
Jul 25 14:21:22 invader2 goes.vnetd[17482]: github.com/platinasystems/go/vnet/ip.(*Main).AddDelNextHop(0xc4201ec068, 0x10000010
d, 0x1000000fb, 0xc42174a090)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip/adjacency.go:47
8 +0x4c5
Jul 25 14:21:22 invader2 goes.vnetd[17482]: github.com/platinasystems/go/vnet/ip4.(*Main).AddDelRouteNextHop(0xc4201ec000, 0xc4
20c24170, 0xc420c24180, 0x1007020801, 0x1, 0x3a296077630f4be9)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip4/fib.go:472 +0x
1cb
Jul 25 14:21:22 invader2 goes.vnetd[17482]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).ip4RouteMsg(0xc420983b00, 0xc42089c820, 0xc42089c801, 0xc4213f4f01, 0x42c444)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:603 +0x1ec
Jul 25 14:21:22 invader2 goes.vnetd[17482]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc420983b00)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:399 +0x5a5
Jul 25 14:21:22 invader2 goes.vnetd[17482]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc420c54000)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
Jul 25 14:21:22 invader2 goes.vnetd[17482]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc4201a0000, 0xc420c54000)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
Jul 25 14:21:22 invader2 goes.vnetd[17482]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc4201a0000, 0x144d760, 0xc4201a0568)
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
Jul 25 14:21:22 invader2 goes.vnetd[17482]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Jul 25 14:21:22 invader2 goes.vnetd[17482]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
Jul 25 14:21:22 invader2 goes.vnetd[17482]: done
Jul 25 14:21:22 invader2 kernel: DMAR: DRHD: handling fault status reg 602
Jul 25 14:21:22 invader2 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr ffc0d000 [fault reason 05] PTE Write access is not set
Jul 25 14:21:22 invader2 kernel: DMAR: [DMA Write] Request device [04:00.0] fault addr ffc0e000 [fault reason 05] PTE Write access is not set
Jul 25 14:21:22 invader2 systemd[1]: Reloading OpenBSD Secure Shell server.
Jul 25 14:21:22 invader2 systemd[1]: Reloaded OpenBSD Secure Shell server.
Jul 25 14:21:22 invader2 kernel: ixgbevf 0000:03:13.3: NIC Link is Up 10 Gbps

**Comment by donnlee** [comment]
From i2 running latest goes and latest coreboot:

```
Jul 27 16:10:46 invader2 goes.qsfp[2242]: QSFP detected in port 27: 40GBASE-CR4, Molex Inc., 1002971051, 527820257
Jul 27 16:10:46 invader2 systemd[1]: Reloaded OpenBSD Secure Shell server.
Jul 27 16:10:46 invader2 goes.vnetd[2251]: runtime error: invalid memory address or nil pointer dereference: goroutine 10 [running]:
Jul 27 16:10:46 invader2 goes.vnetd[2251]: runtime/debug.Stack(0xc421387a48, 0xb31300, 0x1333fe0)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Jul 27 16:10:46 invader2 goes.vnetd[2251]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc4201a2000)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
Jul 27 16:10:46 invader2 goes.vnetd[2251]: panic(0xb31300, 0x1333fe0)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
Jul 27 16:10:46 invader2 goes.vnetd[2251]: github.com/platinasystems/go/vnet/ip.(*Main).AddDelNextHop(0xc420216068, 0x10000010d, 0x1000000f3, 0xc
421f0e494)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip/adjacency.go:485 +0x4c5
Jul 27 16:10:46 invader2 goes.vnetd[2251]: github.com/platinasystems/go/vnet/ip4.(*Main).AddDelRouteNextHop(0xc420216000, 0xc42012f590, 0xc42012f
5a0, 0x307010801, 0xc400000001, 0xc420228218)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:504 +0x1cb
Jul 27 16:10:46 invader2 goes.vnetd[2251]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).ip4RouteMsg(0xc420cd2000, 0xc4205e3860, 0xc4205
e3801, 0x1, 0x42c444)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:607 +0x1ec
Jul 27 16:10:46 invader2 goes.vnetd[2251]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc420cd2000)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:403 +0x5a5
Jul 27 16:10:46 invader2 goes.vnetd[2251]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc4202c6fc0)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
Jul 27 16:10:46 invader2 goes.vnetd[2251]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc4201a2000, 0xc4202c6fc0)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
Jul 27 16:10:46 invader2 goes.vnetd[2251]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc4201a2000, 0x1490fa0, 0xc4201a25a8)
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
Jul 27 16:10:46 invader2 goes.vnetd[2251]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Jul 27 16:10:46 invader2 goes.vnetd[2251]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
Jul 27 16:10:46 invader2 goes.qsfp[2242]: QSFP detected in port 26: 100GBASE-CR4, Molex Inc., 1002971301, 527120016
Jul 27 16:10:46 invader2 systemd[1]: Reloading OpenBSD Secure Shell server.
Jul 27 16:10:46 invader2 systemd[1]: Reloaded OpenBSD Secure Shell server.
Jul 27 16:10:46 invader2 goes.qsfp[2242]: QSFP detected in port 29: 40GBASE-CR4, Molex Inc., 1002971051, 527820185
