### ISSUE TITLE
[sr-iov] index out of range: goroutine 37

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#66]
i2 was happily running in sr-iov mode and forwarding through a docker container.
Then I talked to dlobete about another issue. When I returned to i2, it wasn't forwarding anymore.
I did `goes status` which showed vnet was dead.
And saw `index out of range` in syslog.

Start with i2 ok.  Here our sr1 (server 1) is pinging i7 thru i2:

```
platina@sr1:~$ ping 10.9.1.7
PING 10.9.1.7 (10.9.1.7) 56(84) bytes of data.
64 bytes from 10.9.1.7: icmp_seq=1 ttl=63 time=0.559 ms
64 bytes from 10.9.1.7: icmp_seq=2 ttl=63 time=0.457 ms
64 bytes from 10.9.1.7: icmp_seq=3 ttl=63 time=0.325 ms
^C
```

Then I had a chat with Don for about 5m.
Then returned to sr1 and saw pings failing:

```
platina@sr1:~$ ping 10.9.1.7
PING 10.9.1.7 (10.9.1.7) 56(84) bytes of data.
From 10.0.3.111 icmp_seq=1 Destination Host Unreachable
From 10.0.3.111 icmp_seq=2 Destination Host Unreachable
From 10.0.3.111 icmp_seq=3 Destination Host Unreachable
^C
```

Checked goes:
```
donn@invader2:~/workspace/docker/gobgp$ sudo goes status                                                                                         GOES status
======================
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - Not OK
status: vnetd daemon not responding
donn@invader2:~/workspace/docker/gobgp$ 
```

checked syslog:
```
Jul 27 16:24:57 invader2 goes.vnetd[11746]: runtime error: index out of range: goroutine 37 [running]:
Jul 27 16:24:57 invader2 goes.vnetd[11746]: runtime/debug.Stack(0xc4202079a0, 0xb31300, 0x1334020)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc420194000)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
Jul 27 16:24:57 invader2 goes.vnetd[11746]: panic(0xb31300, 0x1334020)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/fe1/internal/fe1a.(*adjacency_pipe).delete_adj(0xc420791f88, 0xc42078f930,
0xc4201e9068, 0xc400000056)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/fe1/internal/fe1a/fib.go:317 +0x33c
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).adj_add_del(0xc42077a000, 0xc4201e9068, 0x1000000
56)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/fe1/internal/fe1a/fib.go:344 +0x8b
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/fe1/internal/fe1a.(*fe1a).(github.com/platinasystems/fe1/internal/fe1a.adj_
add_del)-fm(0xc4201e9068, 0x100000056)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/fe1/internal/fe1a/fib.go:120 +0x45
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/vnet/ip.(*Main).callAdjAddDelHooks(0xc4201e9068, 0x100000056)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip/adjacency.go:636 +0x77
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/vnet/ip.(*Main).CallAdjDelHooks(0xc4201e9068, 0x56)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip/adjacency.go:640 +0x38
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/vnet/ip.(*Main).DelAdj(0xc4201e9068, 0x5600000056)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip/adjacency.go:570 +0x33
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/vnet/ethernet.(*ipNeighborMain).AddDelIpNeighbor(0xc42009b1e8, 0xc4201e9068, 0xc421cfdbc0, 0x1107010901, 0x7f3e00000001, 0x200f2540)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ethernet/neighbor.go:95 +0x2ac
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).ip4NeighborMsg(0xc420507980, 0xc4200f2620, 0xc4200f2620, 0xc4d001)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:545 +0x2f2
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc420507980)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:412 +0x70e
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc4201bc000)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420194000, 0xc4201bc000)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
Jul 27 16:24:57 invader2 goes.vnetd[11746]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420194000, 0x1490fa0, 0xc4201945a8)
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
Jul 27 16:24:57 invader2 goes.vnetd[11746]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Jul 27 16:24:57 invader2 goes.vnetd[11746]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
```

**Comment by donnlee** [comment]
Was able to repro.
Started with a fresh goes-restart
Setup docker interfaces/IPs
Start ping
Wait about 5m
pings start failing
check vnet: it's dead.

Same syslog msg.

sr1----[i2 container]-------[i7 container]

sr1 is pinging i7

@dlobete suspects it may be arp timeout related.

**Comment by donnlee** [comment]
Did another test, this time without any ping traffic.

goes restart
wait 7 mins
check vnet --> OK
start docker containers & move 3 interfaces into 2 containers.
wait 6 mins (17:38)
check vnet --> Dead (same syslog msgs)

Syslog says panic happened at 17:32, or very close to when containers were started and interfaces moved.

**Comment by donnlee** [comment]
Still happens with top-of-tree code.
restart goes
check it's running
wait about 5 mins
try sho ip fib  (fails)
see index out of range in syslog.

7/13 code is stable enough for sriov demo.

**Comment by dlobete** [comment]
What's happening in this problem is the delete_adj() call is being handed an adjacency_pipe.rx structure whose l3_if_index is invalid (0xffff) so when an index is attempted we get a runtime panic. We need to look at wip branch development in this area to determine if the functionality will change or is a common issue in both branches.

**Comment by dlobete** [comment]
Verified in this rig that this commit addressed it. Will let Donn do final verification and close:

commit dd1093f7ccb67b70371a113879276abab946963a
Author: Don Lobete <dlobete@platinasystems.com>
Date:   Fri Aug 4 11:05:12 2017 -0700

**Comment by donnlee** [comment]
I confirmed this is fixed.
Started with old a96d25cec25e461c078aa676bfd8adb75a3eb7b7 version.  Confirm pings die after a few mins with same panic.
Installed today's build d3cb5954b60b281f1536701da4e3af09fcbece89
Re-test:  Ping test is ok after 15 mins.

There's something unique to i2 (even after Jason swapped the hw) because i7 running old a96d25cec25e461c078aa676bfd8adb75a3eb7b7 code doesn't have this issue.

Also, a new problem may be present (perhaps unrelated):  I can no longer get overlapping addresses on 2 containers working.  One container can ping, but other container cannot. Same ip address used on both containers.  This worked OK on old code.
