### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#8]
Caught this once during “goes start”; very rare.  Had an overnight loop testing something else with 2500 loops of stop/start on Invader7, and saw this just once.

This is happening in redisd.go around.

func (cmd *cmd) Main(args ...string)
…
        err = Hook(pub)
        pub <- "redis.ready: true"
        close(pub)
…

More often I’ve seen this fail with just returning err = ““read: no such device or address” on invader2.  
Logging as a separate issue for now, though could be related.

Syslog (extra debug prints):

Jan  5 22:04:29 invader7 goes.redisd[17309]: goes.Main []
Jan  5 22:04:29 invader7 goes.redisd[17309]: new arg =  [redisd]
Jan  5 22:04:29 invader7 goes.redisd[17309]: next command g := byName[redisd]
Jan  5 22:04:29 invader7 goes.redisd[17309]: g.Kind.IsDaemon() = true
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main Hello==========================
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main finished varrun stuffs==========================
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main finished starting server===/run/goes/socks/redisd
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main finished chgroup adm===/run/goes/socks/redisd
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main finished assign, unassign===/run/goes/socks/redisd
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main published hostname = invader7
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main published machine = platina-mk1
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main published cmdline.BOOT_IMAGE = /boot/vmlinuz-4.6.0-rc2-platina-mk1-amd64
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main published cmdline.console = ttyS0,115200
Jan  5 22:04:29 invader7 goes.redisd[17309]: listen: /run/goes/socks/redisd
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main published cmdline.quiet = true
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main published cmdline.ro = true
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main published cmdline.root = UUID=93576419-075c-46f1-a4b6-8b71ba5de647
Jan  5 22:04:29 invader7 goes.redisd[17309]: redisd.main published cmdline.video = off
Jan  5 22:04:29 invader7 goes.redisd[17309]: listen: [127.0.0.1%lo]:6379
Jan  5 22:04:29 invader7 goes.redisd[17309]: listen: [::1%lo]:6379
Jan  5 22:04:29 invader7 goes.redisd[17309]: listen: [192.168.101.127%eth0]:6379
Jan  5 22:04:29 invader7 goes.redisd[17309]: listen: [fe80::46:8aff:fe00:9f4%eth0]:6379
Jan  5 22:04:30 invader7 goes.redisd[17309]: fatal error: concurrent map read and map write
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 7 [running]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.throw(0xb332a7, 0x21)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420047660 sp=0xc420047640
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.mapaccess1_faststr(0xa39740, 0xc4201a2a50, 0xc42024ce80, 0x15, 0x1)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/hashmap_fast.go:201 +0x4f3 fp=0xc4200476c0 sp=0xc420047660
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/internal/required/redisd.(*Redisd).Hget(0xc420166120, 0xc420239bc0, 0x7, 0xc42024ce80, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/required/redisd/redisd.go:461 +0x124 fp=0xc4200477e8 sp=0xc4200476c0
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.call128(0xc42006fce0, 0xc420136320, 0xc420055220, 0x2800000050)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/asm_amd64.s:481 +0x66 fp=0xc420047878 sp=0xc4200477e8
Jan  5 22:04:30 invader7 goes.redisd[17309]: reflect.Value.call(0xc42014a380, 0xc420136320, 0x13, 0xb1b482, 0x4, 0xc42006b320, 0x3, 0x4, 0x9dc4c0, 0xc420239c20, ...)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/reflect/value.go:434 +0x5c8 fp=0xc420047bc8 sp=0xc420047878
Jan  5 22:04:30 invader7 goes.redisd[17309]: reflect.Value.Call(0xc42014a380, 0xc420136320, 0x13, 0xc42006b320, 0x3, 0x4, 0x54, 0x1f, 0x1f)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420047c30 sp=0xc420047bc8
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).handlerFn.func1(0xc420236600, 0xc420133e30, 0xc420239bbc, 0x4, 0xc4201dacb8)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/auto.go:94 +0xb02 fp=0xc420047e48 sp=0xc420047c30
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Apply(0xc420202780, 0xc420236600, 0x0, 0x0, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/handler.go:42 +0xfc fp=0xc420047e88 sp=0xc420047e48
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).ServeClient(0xc420202780, 0x1212560, 0xc4200241c0, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:133 +0x24e fp=0xc420047f78 sp=0xc420047e88
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.goexit()
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420047f80 sp=0xc420047f78
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Serve
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:82 +0xf8
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 1 [chan send]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: main.getEepromData(0xc4201a6480, 0x26, 0xc4200459c8)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/main/goes-platina-mk1/main.go:164 +0x748
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/internal/required/redisd.(*cmd).Main(0xc420166120, 0xc42000c220, 0x2, 0x2, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/required/redisd/redisd.go:242 +0xf97
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/internal/goes.(mainer).Main-fm(0xc42000c220, 0x0, 0x0, 0xc420167e60, 0xc420045b70)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/goes/goes.go:245 +0x4d
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/internal/goes.ByName.Main(0xc42013e720, 0xc42000c220, 0x0, 0x0, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/goes/goes.go:214 +0xbb0
Jan  5 22:04:30 invader7 goes.redisd[17309]: main.main()
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/main/goes-platina-mk1/main.go:85 +0x442
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 17 [syscall, locked to thread]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.goexit()
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 5 [syscall]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: os/signal.signal_recv(0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/sigqueue.go:116 +0x157
Jan  5 22:04:30 invader7 goes.redisd[17309]: os/signal.loop()
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by os/signal.init.1
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 18 [select, locked to thread]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.gopark(0xb8ee70, 0x0, 0xb1dfbe, 0x6, 0x18, 0x2)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/proc.go:259 +0x13a
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.selectgoImpl(0xc420022730, 0x0, 0x18)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/select.go:423 +0x11d9
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.selectgo(0xc420022730)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/select.go:238 +0x1c
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.ensureSigM.func1()
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
Jan  5 22:04:30 invader7 goes.redisd[17309]: runtime.goexit()
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 19 [chan receive]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/internal/goes.(*Goes).wait(0xc420167440, 0xc420167e60)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/goes/goes.go:279 +0x70
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by github.com/platinasystems/go/internal/goes.ByName.Main
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/goes/goes.go:212 +0xe9c
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 20 [IO wait]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.runtime_pollWait(0x7f9a30bfa658, 0x72, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/netpoll.go:160 +0x59
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).wait(0xc420168450, 0x72, 0xc42001ce40, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).waitRead(0xc420168450, 0x120a560, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*netFD).accept(0xc4201683f0, 0x0, 0x1208c60, 0xc4200d3200)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_unix.go:419 +0x238
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*UnixListener).accept(0xc420147b60, 0x0, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/unixsock_posix.go:158 +0x32
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*UnixListener).Accept(0xc420147b60, 0xc420147b20, 0x19, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/unixsock.go:229 +0x49
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/internal/sockfile.(*RpcServer).listen(0xc4201b4990)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/sockfile/sockfile.go:132 +0x7b
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by github.com/platinasystems/go/internal/sockfile.NewRpcServer
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/sockfile/sockfile.go:96 +0xe3
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 22 [runnable]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/internal/required/redisd.(*cmd).Main.func2(0xc420166120, 0xc4201a6480)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/required/redisd/redisd.go:210 +0x5d
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by github.com/platinasystems/go/internal/required/redisd.(*cmd).Main
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/required/redisd/redisd.go:215 +0xa9f
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 34 [IO wait]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.runtime_pollWait(0x7f9a30bfa598, 0x72, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/netpoll.go:160 +0x59
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).wait(0xc420204060, 0x72, 0xc42001d640, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).waitRead(0xc420204060, 0x120a560, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*netFD).accept(0xc420204000, 0x0, 0x1208c60, 0xc420222000)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_unix.go:419 +0x238
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*TCPListener).accept(0xc420136170, 0xc42001d728, 0xc42001d738, 0xc42001d718)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*TCPListener).Accept(0xc420136170, 0x1244320, 0xc420136170, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/tcpsock.go:222 +0x49
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Serve(0xc420202000, 0x120dda0, 0xc420136170, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:78 +0xb3
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Start(0xc420202000, 0x0, 0x9)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:60 +0x3d
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by github.com/platinasystems/go/internal/required/redisd.(*Redisd).listen
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/required/redisd/redisd.go:374 +0xc4c
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 35 [IO wait]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.runtime_pollWait(0x7f9a30bfa4d8, 0x72, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/netpoll.go:160 +0x59
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).wait(0xc4202040d0, 0x72, 0xc42021a640, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).waitRead(0xc4202040d0, 0x120a560, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*netFD).accept(0xc420204070, 0x0, 0x1208c60, 0xc420222020)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_unix.go:419 +0x238
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*TCPListener).accept(0xc4201362b8, 0xc42021a728, 0xc42021a738, 0xc42021a718)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*TCPListener).Accept(0xc4201362b8, 0x1244320, 0xc4201362b8, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/tcpsock.go:222 +0x49
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Serve(0xc4202023c0, 0x120dda0, 0xc4201362b8, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:78 +0xb3
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Start(0xc4202023c0, 0x0, 0x8)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:60 +0x3d
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by github.com/platinasystems/go/internal/required/redisd.(*Redisd).listen
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/required/redisd/redisd.go:374 +0xc4c
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 36 [IO wait]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.runtime_pollWait(0x7f9a30bfa418, 0x72, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/netpoll.go:160 +0x59
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).wait(0xc420204140, 0x72, 0xc42021ae40, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).waitRead(0xc420204140, 0x120a560, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*netFD).accept(0xc4202040e0, 0x0, 0x1208c60, 0xc4200d3280)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_unix.go:419 +0x238
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*TCPListener).accept(0xc420136400, 0x4372fe, 0xc42021aef0, 0x6792a8)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*TCPListener).Accept(0xc420136400, 0xb8e338, 0xc420202780, 0x1212560, 0xc4200241c0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/tcpsock.go:222 +0x49
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Serve(0xc420202780, 0x120dda0, 0xc420136400, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:78 +0xb3
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Start(0xc420202780, 0x0, 0xf)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:60 +0x3d
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by github.com/platinasystems/go/internal/required/redisd.(*Redisd).listen
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/required/redisd/redisd.go:374 +0xc4c
Jan  5 22:04:30 invader7 goes.redisd[17309]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: goroutine 37 [IO wait]:
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.runtime_pollWait(0x7f9a30bfa358, 0x72, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/runtime/netpoll.go:160 +0x59
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).wait(0xc4202041b0, 0x72, 0xc42021b640, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*pollDesc).waitRead(0xc4202041b0, 0x120a560, 0xc42000c160)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*netFD).accept(0xc420204150, 0x0, 0x1208c60, 0xc420139c80)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/fd_unix.go:419 +0x238
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*TCPListener).accept(0xc420136548, 0xc42021b728, 0xc42021b738, 0xc42021b718)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
Jan  5 22:04:30 invader7 goes.redisd[17309]: net.(*TCPListener).Accept(0xc420136548, 0x1244320, 0xc420136548, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /usr/local/go/src/net/tcpsock.go:222 +0x49
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Serve(0xc420202b40, 0x120dda0, 0xc420136548, 0x0, 0x0)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:78 +0xb3
Jan  5 22:04:30 invader7 goes.redisd[17309]: github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server.(*Server).Start(0xc420202b40, 0x0, 0x1d)
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/vendor/github.com/platinasystems/go-redis-server/server.go:60 +0x3d
Jan  5 22:04:30 invader7 goes.redisd[17309]: created by github.com/platinasystems/go/internal/required/redisd.(*Redisd).listen
Jan  5 22:04:30 invader7 goes.redisd[17309]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/required/redisd/redisd.go:374 +0xc4c
Jan  5 22:04:30 invader7 goes.redisd[17309]: exit status 2
Jan  5 22:04:40 invader7 goes.goes-daemons[17304]: (platina,redis.ready) timeout

**Comment by fszyang** [comment]
Issue closed.  Fixed by commit 1d32f880018eb408e1530a52f87ace757f202d85

Was able to reproduce concurrent map read/write issue fairly frequently with repeated goes stop/start after commit 23dc8f245807a35d0f796e4040513ab177ac711c, which addressed a separate issue.

After commit 1d32f880018eb408e1530a52f87ace757f202d85, verified fix by repeating 1500+ loops of goes stop/start and all passed.
