### ISSUE TITLE
[SR-IOV] "slice bounds out of range" error after ifup cmd

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#81]
I was bouncing an interface like so:

```
 2021  05/09/17 15:14:03 sudo ifdown eth-3-1
 2022  05/09/17 15:14:07 sudo ifup eth-3-1
```

vnet crashed:
```
donn@invader16:~$ sudo goes stat
GOES status
======================
  Mode            - SRIOV
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - Not OK
status: vnetd daemon not responding
```

 and I saw in syslog:

```
Sep  5 15:14:07 invader16 kernel: ixgbevf 0000:03:10.4: NIC Link is Up 10 Gbps
Sep  5 15:14:07 invader16 goes.vnetd[600]: runtime error: slice bounds out of range: goroutine 37 [running]:
Sep  5 15:14:07 invader16 goes.vnetd[600]: runtime/debug.Stack(0xc4206dba40, 0xbb60e0, 0x1420830)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc420192000)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event
.go:126 +0x72
Sep  5 15:14:07 invader16 goes.vnetd[600]: panic(0xbb60e0, 0x1420830)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/vnet/ip.(*Main).AddDelNextHop(0xc420205068, 0x80000000
a, 0xc400000001, 0x7f8ef54a7e88, 0xc420ed61c0, 0x20081f0901, 0x1)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip/adjacen
cy.go:584 +0x280
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDelRouteNextHop(0xc420096f00, 0xc42
0205000, 0xc420ed61b8, 0xc4081f090a, 0x15819c0, 0xc420ed61c0, 0xc18301, 0x503ea001, 0xc420ed61c0)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go
:704 +0x34b
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/vnet/ip4.(*Main).AddDelRouteNextHop(0xc420205000, 0xc420ed61b8, 0xc420ed61c0, 0x7d081f0901, 0x1, 0xc420145090)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:670 +0x82
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).ip4RouteMsg(0xc420fba000, 0xc420440820, 0xc420440801, 0x1, 0xc42005a400)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:601 +0x44e
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc420fba000)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:422 +0x5dd
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc420fba690)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:116 +0x34
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420192000, 0xc420fba690)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:131 +0x51
Sep  5 15:14:07 invader16 goes.vnetd[600]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420192000, 0x157f1c0, 0xc4201925b0)
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:138 +0x86
Sep  5 15:14:07 invader16 goes.vnetd[600]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Sep  5 15:14:07 invader16 goes.vnetd[600]:         /home/jenkins/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:151 +0x124
```

Version:
```
    version: e9b5e22b1b68e229bc752d526b4aad697619ff52

**Comment by jignesh045** [comment]
Issue verification status: Verified

Issue status: Not reproduced

Issue verified in below build

```
root@invader44:/# goes version
github.com/platinasystems/go: v0.41-313-g96fcd2e1
github.com/platinasystems/fe1: v0.2-526-gaa6b634
github.com/platinasystems/firmware-fe1a: v0.2
root@invader44:/#
root@invader44:/# goes hget platina-mk1 packages | grep version:
    version: 96fcd2e13b9d751a95eda8faa60e4974e8143765
    version: aa6b634a0548a66703fd379e26677c12263f752a
    version: 60f39141fbbf78ddb2260dba74c68f2789374f18
root@invader44:/#
root@invader44:/#
root@invader44:/# dpkg --list | grep kernel
ii  kmod                           18-3                             amd64        tools for managing Linux kernel modules
ii  libdrm2:amd64                  2.4.58-2                         amd64        Userspace interface to kernel DRM services -- runtime
ii  linux-image-4.13.0-platina-mk1 4.13-129-g34f08d37ef9c           amd64        Linux kernel, version 4.13.0-platina-mk1
ii  rsyslog                        8.4.2-1+deb8u2                   amd64        reliable system and kernel logging daemon
root@invader44:/#
```

Steps: 

1. Executed below script

```
root@invader43:/home/jignesh# cat ifup1.sh
#! /bin/bash
for (( i=1; i <=100; i++ ))
        do
          ifdown eth-3-1
          ifup eth-3-1
        done

root@invader43:/home/jignesh#

root@invader43:/home/jignesh# ./ifup1.sh
root@invader43:/home/jignesh#
```
2. Check GoES status & syslog. GoES status is OK & no panic log found in syslog.

```
root@invader43:/home/jignesh# goes status
GOES status
======================
  Mode            - SRIOV
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK
root@invader43:/home/jignesh#
```
